"""Structural tests for the VCUB ATM Swaptions template parser (Issue #181).

Every fixture here is **synthetic**: the labels are ordinary tenor buckets
and the numbers are generated by :func:`_synthetic_value` from row/column
indices. Nothing in this file is a Bloomberg screen capture, a Bloomberg
screen layout measurement, or a live market quote -- this repository is
public, so the real screenshot stays operator-local and is supplied by path
at live acceptance.

The token layer is where these tests bite, because that is the parser's own
contract: a reader hands it text with boxes, and everything Issue #181 cares
about (order, cell mapping, fail-closed behaviour, scale/crop independence)
is decided from those boxes alone. The small end-to-end image test lives in
``test_bloomberg_vcub_ocr.py``.
"""

from __future__ import annotations

from collections.abc import Sequence

import pytest

from shiori_pricing_lab.data.bloomberg_vcub_atm_template import (
    parse_vcub_atm_tokens,
)
from shiori_pricing_lab.data.bloomberg_vcub_capture import (
    METADATA_FIELDS,
    VCUBCaptureProvenance,
    VCUBCaptureStatus,
    VCUBTextToken,
)

# ---------------------------------------------------------------------------
# Synthetic fixture
# ---------------------------------------------------------------------------

EXPIRY_LABELS = ("1Mo", "2Mo", "3Mo", "6Mo", "9Mo", "1Yr", "18Mo", "2Yr")
TENOR_LABELS = ("1Yr", "2Yr", "3Yr", "4Yr", "5Yr", "6Yr")

_HEADER_Y = 110.0
_FIRST_ROW_Y = 140.0
_ROW_PITCH = 28.0
_FIRST_COLUMN_X = 160.0
_COLUMN_PITCH = 80.0
_ANCHOR_X = 40.0
_GLYPH_HEIGHT = 14.0


def _synthetic_value(row_index: int, column_index: int) -> float:
    """A made-up, strictly distinct number per intersection -- never a real quote."""

    return round(80.0 + row_index * 1.5 + column_index * 0.25, 2)


def _token(
    text: str,
    x_center: float,
    y_center: float,
    *,
    width: float | None = None,
    height: float | None = None,
) -> VCUBTextToken:
    width = len(text) * 8.0 if width is None else width
    height = _GLYPH_HEIGHT if height is None else height
    return VCUBTextToken(
        text=text,
        left=x_center - width / 2.0,
        top=y_center - height / 2.0,
        width=width,
        height=height,
        confidence=0.99,
    )


def _row_y(row_index: int) -> float:
    return _FIRST_ROW_Y + row_index * _ROW_PITCH


def _column_x(column_index: int) -> float:
    return _FIRST_COLUMN_X + column_index * _COLUMN_PITCH


#: Word boxes inside one phrase sit about half a character width apart in
#: rendered text. The original version of this fixture spread them four times
#: wider than that, which read as five separate widgets once field boundaries
#: were derived from real gaps -- the fixture was unrealistic, not the rule.
_WORD_GAP = 4.0


def _word_row(words: Sequence[str], y: float, left: float = 40.0) -> list[VCUBTextToken]:
    """One header line laid out with realistic intra-phrase spacing."""

    tokens: list[VCUBTextToken] = []
    cursor = left
    for word in words:
        width = len(word) * 8.0
        tokens.append(_token(word, cursor + width / 2.0, y, width=width))
        cursor += width + _WORD_GAP
    return tokens


def metadata_tokens() -> list[VCUBTextToken]:
    """The header context above the matrix, as separate word tokens."""

    return (
        _word_row(("USD", "RFR", "BVOL", "Cube", "(Default)"), 20.0)
        + _word_row(("ATM", "Swaptions", "Mid", "08/18/26"), 50.0)
        + _word_row(("Type", "Normal", "Vol", "(OIS)", "Source", "BVOL"), 80.0)
    )


def grid_tokens(
    *,
    omit_cells: frozenset[tuple[int, int]] = frozenset(),
    value_overrides: dict[tuple[int, int], str] | None = None,
) -> list[VCUBTextToken]:
    """The matrix itself: the corner anchor, both axes, and every cell.

    Cell centres are nudged right of their header centres so the fixture
    never accidentally proves the mapping only for perfectly centred text.
    """

    value_overrides = value_overrides or {}
    tokens = [_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0)]
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index, label in enumerate(EXPIRY_LABELS):
        tokens.append(_token(label, _ANCHOR_X + 14.0, _row_y(row_index)))
    for row_index in range(len(EXPIRY_LABELS)):
        for column_index in range(len(TENOR_LABELS)):
            if (row_index, column_index) in omit_cells:
                continue
            text = value_overrides.get(
                (row_index, column_index),
                f"{_synthetic_value(row_index, column_index):.2f}",
            )
            tokens.append(
                _token(text, _column_x(column_index) + 6.0, _row_y(row_index))
            )
    return tokens


def outside_grid_tokens() -> list[VCUBTextToken]:
    """Chrome that must never become a cell: a footer and a right-hand caption."""

    return [
        _token("Zoom", 120.0, 400.0),
        _token("100%", 175.0, 400.0),
        _token("Scroll", 720.0, _row_y(2)),
    ]


def canonical_tokens(**kwargs) -> list[VCUBTextToken]:
    return metadata_tokens() + grid_tokens(**kwargs) + outside_grid_tokens()


def provenance(**overrides) -> VCUBCaptureProvenance:
    fields = {
        "source_reference": "vcub_atm_usd.png",
        "source_image_sha256": "a" * 64,
        "source_image_bytes": 4096,
        "captured_at": "2026-08-18T09:30:00Z",
    }
    fields.update(overrides)
    return VCUBCaptureProvenance(**fields)


def parse(tokens) -> object:
    return parse_vcub_atm_tokens(tokens, provenance=provenance())


def transform(tokens, *, scale: float = 1.0, dx: float = 0.0, dy: float = 0.0):
    """Re-render the same screen at another zoom/crop, as a real recapture would."""

    return [
        VCUBTextToken(
            text=token.text,
            left=token.left * scale + dx,
            top=token.top * scale + dy,
            width=token.width * scale,
            height=token.height * scale,
            confidence=token.confidence,
        )
        for token in tokens
    ]


def codes(issues) -> list[str]:
    return [issue.code for issue in issues]


# ---------------------------------------------------------------------------
# 1-4: the canonical grid, its axis order, and every cell mapping
# ---------------------------------------------------------------------------


def test_canonical_synthetic_atm_grid_parses_with_no_blocking_errors() -> None:
    capture = parse(canonical_tokens())

    assert codes(capture.blocking_errors) == []
    assert capture.grid is not None
    assert capture.review_status is VCUBCaptureStatus.PENDING_REVIEW


def test_expiry_labels_keep_the_screen_order_down_the_rows() -> None:
    capture = parse(canonical_tokens())

    assert capture.grid.expiry_labels == EXPIRY_LABELS


def test_tenor_labels_keep_the_screen_order_across_the_columns() -> None:
    capture = parse(canonical_tokens())

    assert capture.grid.tenor_labels == TENOR_LABELS


def test_every_value_lands_on_its_own_expiry_and_tenor_intersection() -> None:
    capture = parse(canonical_tokens())

    for row_index, expiry in enumerate(EXPIRY_LABELS):
        for column_index, tenor in enumerate(TENOR_LABELS):
            assert capture.grid.value_at(expiry, tenor) == pytest.approx(
                _synthetic_value(row_index, column_index)
            ), f"{expiry} x {tenor} is not the value drawn at that intersection"


def test_a_shuffled_token_order_changes_nothing_because_placement_is_geometric() -> None:
    tokens = canonical_tokens()
    shuffled = list(reversed(tokens))

    assert parse(shuffled).grid.to_dict() == parse(tokens).grid.to_dict()


# ---------------------------------------------------------------------------
# 5-7: missing and duplicated anchors fail closed
# ---------------------------------------------------------------------------


def test_a_missing_expiry_anchor_fails_closed_with_no_grid() -> None:
    tokens = [token for token in canonical_tokens() if token.text != "Expiry"]

    capture = parse(tokens)

    assert capture.grid is None
    assert "EXPIRY_ANCHOR_UNRESOLVED" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_missing_atm_swaptions_tab_anchor_fails_closed() -> None:
    tokens = [token for token in canonical_tokens() if token.text != "Swaptions"]

    capture = parse(tokens)

    assert "ATM_SWAPTIONS_TAB_UNRESOLVED" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_duplicated_expiry_anchor_fails_closed_rather_than_picking_one() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, 400.0, width=44.0))

    capture = parse(tokens)

    assert capture.grid is None
    assert "EXPIRY_ANCHOR_AMBIGUOUS" in codes(capture.blocking_errors)


def test_a_duplicated_tenor_header_fails_closed() -> None:
    tokens = metadata_tokens() + outside_grid_tokens()
    for token in grid_tokens():
        if token.text == "4Yr" and abs(token.y_center - _HEADER_Y) < 1.0:
            token = _token("3Yr", token.x_center, token.y_center)
        tokens.append(token)

    capture = parse(tokens)

    assert capture.grid is None
    assert "DUPLICATE_TENOR_LABEL" in codes(capture.blocking_errors)


def test_a_duplicated_expiry_label_fails_closed() -> None:
    tokens = metadata_tokens() + outside_grid_tokens()
    for token in grid_tokens():
        if token.text == "6Mo" and abs(token.x_center - (_ANCHOR_X + 14.0)) < 1.0:
            token = _token("3Mo", token.x_center, token.y_center)
        tokens.append(token)

    capture = parse(tokens)

    assert capture.grid is None
    assert "DUPLICATE_EXPIRY_LABEL" in codes(capture.blocking_errors)


def test_a_non_tenor_token_on_the_header_line_fails_closed() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("Beta", _column_x(6), _HEADER_Y))

    capture = parse(tokens)

    assert "TENOR_HEADER_UNEXPECTED_TOKEN" in codes(capture.blocking_errors)


# ---------------------------------------------------------------------------
# 8-9: malformed and non-finite numbers
# ---------------------------------------------------------------------------


def test_a_malformed_numeric_cell_is_surfaced_and_left_unresolved() -> None:
    capture = parse(canonical_tokens(value_overrides={(2, 3): "8S.15"}))

    blocking = [
        issue for issue in capture.blocking_errors if issue.code == "MALFORMED_NUMERIC_CELL"
    ]
    assert [(issue.expiry, issue.tenor) for issue in blocking] == [("3Mo", "4Yr")]
    assert capture.grid.value_at("3Mo", "4Yr") is None
    assert not capture.can_confirm


@pytest.mark.parametrize("text", ["NaN", "Infinity", "-inf", "1e999"])
def test_a_non_finite_or_exponent_cell_never_becomes_a_value(text: str) -> None:
    capture = parse(canonical_tokens(value_overrides={(1, 1): text}))

    assert codes(capture.blocking_errors) != []
    assert capture.grid.value_at("2Mo", "2Yr") is None
    assert not capture.can_confirm


def test_a_thousands_separated_number_still_reads_as_one_value() -> None:
    capture = parse(canonical_tokens(value_overrides={(0, 0): "1,234.50"}))

    assert capture.grid.value_at("1Mo", "1Yr") == pytest.approx(1234.50)
    assert codes(capture.blocking_errors) == []


# ---------------------------------------------------------------------------
# 10-11: holes must not shift anything
# ---------------------------------------------------------------------------


def test_a_missing_interior_cell_cannot_shift_the_cells_after_it() -> None:
    capture = parse(canonical_tokens(omit_cells=frozenset({(3, 2)})))

    assert capture.grid.value_at("6Mo", "3Yr") is None
    for column_index, tenor in enumerate(TENOR_LABELS):
        if tenor == "3Yr":
            continue
        assert capture.grid.value_at("6Mo", tenor) == pytest.approx(
            _synthetic_value(3, column_index)
        )


def test_a_partial_row_cannot_shift_the_rows_below_it() -> None:
    omitted = frozenset({(4, 1), (4, 2), (4, 3), (4, 4), (4, 5)})

    capture = parse(canonical_tokens(omit_cells=omitted))

    assert capture.grid.value_at("9Mo", "1Yr") == pytest.approx(
        _synthetic_value(4, 0)
    )
    for tenor in TENOR_LABELS[1:]:
        assert capture.grid.value_at("9Mo", tenor) is None
    for row_index, expiry in enumerate(EXPIRY_LABELS[5:], start=5):
        for column_index, tenor in enumerate(TENOR_LABELS):
            assert capture.grid.value_at(expiry, tenor) == pytest.approx(
                _synthetic_value(row_index, column_index)
            )


def test_an_unresolved_intersection_is_reported_to_the_trader_as_a_warning() -> None:
    capture = parse(canonical_tokens(omit_cells=frozenset({(2, 3)})))

    unresolved = [issue for issue in capture.warnings if issue.code == "UNRESOLVED_CELL"]
    assert [(issue.expiry, issue.tenor) for issue in unresolved] == [("3Mo", "4Yr")]


def test_a_row_shifted_against_the_detected_columns_fails_closed() -> None:
    """Half a column of drift must be refused, never rounded to a neighbour."""

    tokens = metadata_tokens() + outside_grid_tokens()
    for token in grid_tokens():
        drifted = abs(token.y_center - _row_y(3)) < 1.0 and token.x_center > _FIRST_COLUMN_X - 40
        tokens.append(
            _token(token.text, token.x_center + _COLUMN_PITCH / 2.0, token.y_center)
            if drifted
            else token
        )

    capture = parse(tokens)

    assert "CELL_POSITION_AMBIGUOUS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_dropped_row_label_fails_closed_instead_of_shifting_a_row_up() -> None:
    """The one way a value could land a row out: a label the reader missed."""

    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == "6Mo" and abs(token.x_center - (_ANCHOR_X + 14.0)) < 1.0)
    ]

    capture = parse(tokens)

    assert codes(capture.blocking_errors) != []
    assert not capture.can_confirm


def test_a_dropped_tenor_header_fails_closed_instead_of_shifting_a_column_left() -> None:
    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == "3Yr" and abs(token.y_center - _HEADER_Y) < 1.0)
    ]

    capture = parse(tokens)

    assert codes(capture.blocking_errors) != []
    assert not capture.can_confirm


@pytest.mark.parametrize("dropped_label,row_index", [("1Mo", 0), ("2Yr", 7)])
def test_a_dropped_edge_row_label_fails_closed_instead_of_truncating_the_grid(
    dropped_label: str, row_index: int
) -> None:
    """Codex review, PR #182.

    A dropped label at the *top* or *bottom* of the axis leaves no gap
    behind -- the axis simply ends one row early -- so the pitch check
    cannot see it. Without a guard, that row's values fall outside every
    band and are waved through as page chrome, producing a silently
    truncated grid that a trader could confirm.
    """

    tokens = [
        token
        for token in canonical_tokens()
        if not (
            token.text == dropped_label
            and abs(token.x_center - (_ANCHOR_X + 14.0)) < 1.0
            and abs(token.y_center - _row_y(row_index)) < 1.0
        )
    ]

    capture = parse(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_ROWS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_dropped_interior_label_on_a_four_row_axis_fails_closed() -> None:
    """Codex review, PR #182.

    With only two gaps left to compare, a median is dragged up by the wide
    gap itself, so the regularity check has to measure against the narrowest
    gap instead.
    """

    kept = {0, 1, 2, 3}
    tokens = [token for token in metadata_tokens()]
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index in sorted(kept):
        # The 6Mo label (row 3) is the one the reader missed.
        if row_index != 3:
            tokens.append(
                _token(EXPIRY_LABELS[row_index], _ANCHOR_X + 14.0, _row_y(row_index))
            )
        for column_index in range(len(TENOR_LABELS)):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    _row_y(row_index),
                )
            )

    capture = parse(tokens)

    assert codes(capture.blocking_errors) != []
    assert not capture.can_confirm


def test_a_dropped_edge_row_is_caught_even_when_the_row_pitch_is_uneven() -> None:
    """Codex review round 2, PR #182.

    Pitches of 28px and 44px are uneven but stay inside the regularity
    threshold, so the axis is accepted. A window of one *narrowest* pitch
    then stops short of a dropped bottom row continuing at the wider pitch,
    and its whole set of values would be waved through as chrome.
    """

    narrow, wide = 28.0, 44.0
    row_tops = [_FIRST_ROW_Y, _FIRST_ROW_Y + narrow, _FIRST_ROW_Y + narrow + wide]
    dropped_row_y = row_tops[-1] + wide

    tokens = metadata_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index, row_y in enumerate(row_tops):
        tokens.append(_token(EXPIRY_LABELS[row_index], _ANCHOR_X + 14.0, row_y))
        for column_index in range(len(TENOR_LABELS)):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    row_y,
                )
            )
    # The fourth row's label was missed; only its values were read.
    for column_index in range(len(TENOR_LABELS)):
        tokens.append(
            _token(
                f"{_synthetic_value(3, column_index):.2f}",
                _column_x(column_index) + 6.0,
                dropped_row_y,
            )
        )

    capture = parse(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_ROWS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


@pytest.mark.parametrize("dropped", ["1Yr", "6Yr"])
def test_a_dropped_edge_tenor_header_fails_closed(dropped: str) -> None:
    """The column-axis mirror of the dropped edge row label.

    The row axis needs an explicit window because chrome sits above and
    below a table; the column axis does not, because a number beside the
    matrix is refused at any distance. This pins that asymmetry: losing the
    first or last tenor header must not quietly narrow the surface.
    """

    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == dropped and abs(token.y_center - _HEADER_Y) < 1.0)
    ]

    capture = parse(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_COLUMNS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def _short_axis_tokens(row_count: int, dropped_row: int) -> list[VCUBTextToken]:
    tokens = metadata_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index in range(row_count):
        if row_index != dropped_row:
            tokens.append(
                _token(EXPIRY_LABELS[row_index], _ANCHOR_X + 14.0, _row_y(row_index))
            )
        for column_index in range(len(TENOR_LABELS)):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    _row_y(row_index),
                )
            )
    return tokens


def test_a_dropped_middle_label_on_a_three_row_axis_fails_closed() -> None:
    """The pitch check needs three centres, so on a three-row axis it is
    inactive after a label is lost. The dropped row's values then land on
    the re-spanned boundary, and the ambiguity check refuses them -- which
    is what keeps that blind spot closed."""

    capture = parse(_short_axis_tokens(3, 1))

    assert "CELL_POSITION_AMBIGUOUS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


@pytest.mark.parametrize("dropped_row", [0, 1])
@pytest.mark.parametrize("pitch", [_ROW_PITCH, 100.0, 400.0])
def test_a_dropped_label_on_a_two_row_axis_fails_closed(
    dropped_row: int, pitch: float
) -> None:
    """Losing one of two rows leaves a single centre and no measurable pitch.

    Codex review round 4, PR #182: an earlier version of this test used only
    the canonical spacing and passed for the wrong reason -- 28px happens to
    fit inside the window ``_band_edges`` derives from the surviving label's
    own *height*, which no invariant ties to the missing row's spacing. At a
    wider pitch the orphaned row fell outside that window and a one-row grid
    was confirmable. The wide cases are the ones that matter here.
    """

    tokens = metadata_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index in range(2):
        row_y = _FIRST_ROW_Y + row_index * pitch
        if row_index != dropped_row:
            tokens.append(_token(EXPIRY_LABELS[row_index], _ANCHOR_X + 14.0, row_y))
        for column_index in range(len(TENOR_LABELS)):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    row_y,
                )
            )

    capture = parse(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_ROWS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def _grid_with_row_positions(row_positions, labels) -> list[VCUBTextToken]:
    """A well-formed grid whose rows sit exactly where told, values centred."""

    tokens = metadata_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index, (row_y, label) in enumerate(zip(row_positions, labels, strict=True)):
        tokens.append(_token(label, _ANCHOR_X + 14.0, row_y))
        for column_index in range(len(TENOR_LABELS)):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    row_y,
                )
            )
    return tokens


def test_irregular_row_spacing_alone_fails_the_capture_closed() -> None:
    """The pitch guard, isolated from every other guard.

    Found by mutation testing: disabling `_check_pitch_regularity` entirely
    left the whole parser suite green, because every dropped-label case also
    trips the ambiguity check. Here the values sit exactly on their row
    centres and well clear of both boundaries, so nothing else can fire --
    only the spacing itself says a row is missing.
    """

    capture = parse(_grid_with_row_positions([140.0, 168.0, 250.0], EXPIRY_LABELS[:3]))

    assert "ROW_PITCH_IRREGULAR" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_an_axis_that_does_not_increase_in_tenor_fails_closed() -> None:
    """The monotonic-axis check, isolated.

    Also found by mutation testing: nothing required it. Spacing here is
    regular and no value is near a boundary, so the only thing wrong is that
    the labels do not increase down the axis -- which is what a mis-read
    label looks like.
    """

    capture = parse(
        _grid_with_row_positions([140.0, 168.0, 196.0], ("1Mo", "3Mo", "2Mo"))
    )

    assert "EXPIRY_LABELS_NOT_MONOTONIC" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_tenor_headers_that_do_not_increase_fail_closed() -> None:
    tokens = metadata_tokens() + outside_grid_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(("1Yr", "3Yr", "2Yr")):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index in range(3):
        tokens.append(_token(EXPIRY_LABELS[row_index], _ANCHOR_X + 14.0, _row_y(row_index)))
        for column_index in range(3):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    _row_y(row_index),
                )
            )

    capture = parse(tokens)

    assert "TENOR_HEADERS_NOT_MONOTONIC" in codes(capture.blocking_errors)
    assert not capture.can_confirm


@pytest.mark.parametrize("text", ["1e2", "1E2", "8.5e1"])
def test_an_exponent_cell_is_malformed_even_when_it_would_be_finite(text: str) -> None:
    """The regex's exponent exclusion, isolated.

    Mutation testing showed that allowing exponents left the suite green,
    because `1e999` is still caught downstream by the finiteness check. A
    *finite* exponent slips past that second line entirely: without this,
    `1e2` would quietly become the value 100 in a cell where VCUB never
    writes one.
    """

    capture = parse(canonical_tokens(value_overrides={(2, 3): text}))

    assert "MALFORMED_NUMERIC_CELL" in codes(capture.blocking_errors)
    assert capture.grid.value_at("3Mo", "4Yr") is None
    assert not capture.can_confirm


# ---------------------------------------------------------------------------
# Live-capture geometry (Issue #181 acceptance run 1)
#
# The first real VCUB capture failed closed on EXPIRY_ROWS_NOT_ORDERABLE for
# '2Mo'/'3Mo'. The grid on a real screen is dense enough that adjacent expiry
# labels' detected boxes bleed into one another while their centres stay a
# full row apart. These fixtures reproduce that *proportion* -- boxes taller
# than the row pitch -- with synthetic labels and generated numbers. No live
# screenshot and no market data from it is reproduced here.
# ---------------------------------------------------------------------------

_DENSE_ROW_PITCH = 11.0
_DENSE_GLYPH_HEIGHT = 13.0  # taller than the pitch: adjacent boxes overlap


def _dense_grid_tokens(glyph_height: float = _DENSE_GLYPH_HEIGHT) -> list[VCUBTextToken]:
    tokens = metadata_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index, label in enumerate(EXPIRY_LABELS):
        row_y = _FIRST_ROW_Y + row_index * _DENSE_ROW_PITCH
        tokens.append(
            _token(label, _ANCHOR_X + 14.0, row_y, height=glyph_height)
        )
        for column_index in range(len(TENOR_LABELS)):
            tokens.append(
                _token(
                    f"{_synthetic_value(row_index, column_index):.2f}",
                    _column_x(column_index) + 6.0,
                    row_y,
                    height=glyph_height,
                )
            )
    return tokens


def test_a_dense_grid_whose_row_boxes_overlap_still_parses() -> None:
    """The live acceptance failure: overlap is not ambiguity.

    Adjacent rows' boxes overlap here by 2px against an 11px pitch, exactly
    the shape the real screen produced. Refusing any overlap blocked a
    capture whose order was perfectly legible.
    """

    capture = parse(_dense_grid_tokens())

    assert codes(capture.blocking_errors) == []
    assert capture.grid.expiry_labels == EXPIRY_LABELS
    assert capture.can_confirm


def test_relaxing_overlap_moved_no_value_out_of_its_own_cell() -> None:
    """The guarantee that matters: order is read from centres, and so is
    every placement, so tolerating box bleed cannot shift a cell."""

    capture = parse(_dense_grid_tokens())

    for row_index, expiry in enumerate(EXPIRY_LABELS):
        for column_index, tenor in enumerate(TENOR_LABELS):
            assert capture.grid.value_at(expiry, tenor) == pytest.approx(
                _synthetic_value(row_index, column_index)
            ), f"{expiry} x {tenor} moved once overlapping boxes were allowed"


def test_labels_overlapping_enough_to_read_as_one_row_still_fail_closed() -> None:
    """The relaxation has a floor: boxes that would group into a single text
    line are still refused, so a genuinely unreadable order cannot slip in."""

    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == "2Mo" and abs(token.x_center - (_ANCHOR_X + 14.0)) < 1.0)
    ]
    # '2Mo' redrawn almost on top of '3Mo': centres 3px apart, boxes 14 tall.
    tokens.append(_token("2Mo", _ANCHOR_X + 14.0, _row_y(2) - 3.0))

    capture = parse(tokens)

    assert "EXPIRY_ROWS_NOT_ORDERABLE" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_tenor_headers_overlapping_enough_to_read_as_one_still_fail_closed() -> None:
    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == "2Yr" and abs(token.y_center - _HEADER_Y) < 1.0)
    ]
    tokens.append(_token("2Yr", _column_x(2) - 6.0, _HEADER_Y))

    capture = parse(tokens)

    assert "TENOR_HEADERS_NOT_ORDERABLE" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_an_unevenly_spaced_axis_still_refuses_a_boundary_straddling_value() -> None:
    """Codex review, PR #182.

    Each boundary's ambiguity tolerance must come from the pitch between its
    own two columns. Borrowing a narrower neighbour's pitch shrinks the
    tolerance at a wide boundary, so a genuinely ambiguous value would be
    handed a confident cell.
    """

    narrow, wide = 60.0, 140.0
    centres = [_FIRST_COLUMN_X, _FIRST_COLUMN_X + narrow, _FIRST_COLUMN_X + narrow + wide]
    tokens = metadata_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0))
    for centre, label in zip(centres, ("1Yr", "2Yr", "3Yr"), strict=True):
        tokens.append(_token(label, centre, _HEADER_Y))
    for row_index in range(3):
        tokens.append(_token(EXPIRY_LABELS[row_index], _ANCHOR_X + 14.0, _row_y(row_index)))
    # Straddling the wide boundary: 8% of that boundary's own 140px pitch.
    straddling = (centres[1] + centres[2]) / 2.0 - wide * 0.08
    tokens.append(_token("81.00", straddling, _row_y(0)))

    capture = parse(tokens)

    assert "CELL_POSITION_AMBIGUOUS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_two_values_read_into_one_intersection_fail_closed() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("99.99", _column_x(2) + 2.0, _row_y(1)))

    capture = parse(tokens)

    duplicates = [issue for issue in capture.blocking_errors if issue.code == "DUPLICATE_CELL"]
    assert [(issue.expiry, issue.tenor) for issue in duplicates] == [("2Mo", "3Yr")]
    assert capture.grid.value_at("2Mo", "3Yr") is None


def test_a_number_beside_the_matrix_is_reported_rather_than_placed() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("77.70", 720.0, _row_y(1)))

    capture = parse(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_COLUMNS" in codes(capture.blocking_errors)


# ---------------------------------------------------------------------------
# 12-13: scale and crop independence
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("scale", [0.8, 1.25, 1.5, 2.0])
def test_a_rescaled_capture_maps_every_cell_identically(scale: float) -> None:
    baseline = parse(canonical_tokens()).grid.to_dict()

    rescaled = parse(transform(canonical_tokens(), scale=scale)).grid.to_dict()

    assert rescaled == baseline


@pytest.mark.parametrize("dx,dy", [(-37.0, -52.0), (410.0, 260.0), (-19.5, 8.25)])
def test_a_recropped_or_repositioned_capture_maps_every_cell_identically(
    dx: float, dy: float
) -> None:
    baseline = parse(canonical_tokens()).grid.to_dict()

    moved = parse(transform(canonical_tokens(), dx=dx, dy=dy)).grid.to_dict()

    assert moved == baseline


def test_a_rescaled_and_recropped_capture_still_has_no_blocking_errors() -> None:
    capture = parse(transform(canonical_tokens(), scale=1.75, dx=-140.0, dy=-95.0))

    assert codes(capture.blocking_errors) == []
    assert capture.grid.value_at("3Mo", "4Yr") == pytest.approx(_synthetic_value(2, 3))


def test_small_per_token_jitter_does_not_move_a_value_into_a_neighbouring_cell() -> None:
    """Sub-pixel-ish detection wobble is normal and must not change any mapping."""

    tokens = canonical_tokens()
    jittered = [
        VCUBTextToken(
            text=token.text,
            left=token.left + (index % 5 - 2) * 0.9,
            top=token.top + (index % 3 - 1) * 0.7,
            width=token.width,
            height=token.height,
            confidence=token.confidence,
        )
        for index, token in enumerate(tokens)
    ]

    assert parse(jittered).grid.to_dict() == parse(tokens).grid.to_dict()


# ---------------------------------------------------------------------------
# 14: text outside the grid
# ---------------------------------------------------------------------------


def test_text_outside_the_matrix_never_becomes_a_cell() -> None:
    with_chrome = parse(canonical_tokens())
    without_chrome = parse(metadata_tokens() + grid_tokens())

    assert with_chrome.grid.to_dict() == without_chrome.grid.to_dict()
    assert codes(with_chrome.blocking_errors) == []


def test_a_stray_footer_number_below_the_matrix_is_not_a_cell() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("42.00", _column_x(1), _row_y(len(EXPIRY_LABELS)) + 60.0))

    capture = parse(tokens)

    assert codes(capture.blocking_errors) == []
    assert capture.grid.to_dict() == parse(canonical_tokens()).grid.to_dict()


# ---------------------------------------------------------------------------
# 15: metadata resolves or is explicitly unresolved, never invented
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Live-capture header layout (Issue #181 acceptance run 1)
#
# The real screen packs several widgets onto one line and draws clickable
# actions as "N) Label" beside them. Currency, Curve/Config and Side all read
# Unresolved and Source came back contaminated. These fixtures reproduce that
# text layout -- caret glued to its value, menu actions alongside -- with no
# captured market data.
# ---------------------------------------------------------------------------


def _header_line(text: str, y: float, x: float = 40.0) -> list[VCUBTextToken]:
    tokens: list[VCUBTextToken] = []
    cursor = x
    for word in text.split():
        width = len(word) * 7.0
        tokens.append(
            VCUBTextToken(text=word, left=cursor, top=y, width=width, height=9.0)
        )
        cursor += width + 5.0
    return tokens


def _live_layout_header_tokens() -> list[VCUBTextToken]:
    return (
        _header_line(
            "USD\u25be RFR\u25be USD RFR BVOL Cube (Default)\u25be Mid\u25be Date: 08/19/26",
            20.0,
        )
        + _header_line(
            "9) Analyze Cube 1) Caps/Floors 3) ATM Swaptions 4) OTM Swaptions / SABR", 44.0
        )
        + _header_line(
            "Type Normal Vol (OIS)\u25be Source BVOL\u25be "
            "16) Use This Contributor in Configuration",
            68.0,
        )
    )


def _live_layout_capture():
    return parse(_live_layout_header_tokens() + grid_tokens())


def test_a_caret_glued_to_its_value_no_longer_hides_the_currency_or_side() -> None:
    """Both read Unresolved on a screen that plainly showed them, because the
    dropdown caret came back attached and neither was ever a bare word."""

    metadata = _live_layout_capture().metadata

    assert metadata.currency == "USD"
    assert metadata.side == "Mid"


def test_a_menu_action_beside_a_field_no_longer_contaminates_it() -> None:
    """Source came back as the whole rest of its line, menu entry included."""

    metadata = _live_layout_capture().metadata

    assert metadata.source == "BVOL"
    assert metadata.vol_type == "Normal Vol (OIS)"


def test_the_analyze_cube_menu_entry_no_longer_hides_the_curve_config() -> None:
    """Two occurrences of 'Cube' made the field ambiguous -- but one of them
    is a menu action, not a value."""

    metadata = _live_layout_capture().metadata

    assert metadata.curve_config == "USD RFR BVOL Cube (Default)"


def test_the_live_header_layout_resolves_every_metadata_field() -> None:
    metadata = _live_layout_capture().metadata

    assert metadata.unresolved_fields == ()
    assert metadata.quote_date == "08/19/26"
    assert metadata.tab == "ATM Swaptions"


@pytest.mark.parametrize(
    "curve_name",
    [
        "USD RFR BVOL Cube (Default)",                   # the live screen's own name
        "USD SOFR OIS Bloomberg BVOL Cube (Default)",    # more words than the old bound
        "USD RFR/OIS BVOL Cube (Default)",               # punctuation inside the name
        "USD RFR+OIS BVOL Cube (Default)",               # punctuation never enumerated
        "USD RFR|OIS BVOL Cube (Default)",
        "USD RFR (OIS) BVOL Cube (Default)",             # parentheses inside the name
        "A B C D E F G H I J K L BVOL Cube (Default)",   # far longer than any bound
    ],
)
def test_a_curve_config_name_is_captured_whole(curve_name: str) -> None:
    """Codex review, PR #182 (twice).

    The name used to be found by searching the joined line for a bounded
    phrase, so every character not enumerated in its character class became
    a false field boundary: the match restarted after it and a *truncated*
    Bloomberg name was stored as the resolved value. Enumerating more
    characters only moved the hole -- ``+``, ``|`` and an inner ``(OIS)``
    all still truncated.

    The name is now read from the tokens, extended leftwards to a real
    widget boundary, so a match cannot restart in the middle of one.
    """

    tokens = _header_line(f"CCY\u25be IDX\u25be {curve_name}\u25be Mid\u25be", 20.0)
    tokens += _header_line("ATM Swaptions", 44.0)
    tokens += grid_tokens()

    assert parse(tokens).metadata.curve_config == curve_name


def _curve_line_tokens(words: Sequence[str], y: float = 20.0) -> list[VCUBTextToken]:
    """A header line with one token per supplied box, tightly spaced."""

    tokens: list[VCUBTextToken] = []
    cursor = 40.0
    for word in words:
        width = max(len(word), 1) * 7.0
        tokens.append(
            VCUBTextToken(text=word, left=cursor, top=y, width=width, height=9.0)
        )
        cursor += width + 4.0
    return tokens


@pytest.mark.parametrize(
    "boxes,expected",
    [
        # However the reader chooses to group the suffix, the name is whole.
        ((["CCY\u25be", "USD", "RFR", "BVOL", "Cube", "(Default)"]), "USD RFR BVOL Cube (Default)"),
        (
            (["CCY\u25be", "USD", "RFR", "BVOL", "Cube", "(", "Default", ")"]),
            "USD RFR BVOL Cube (Default)",
        ),
        (
            (["CCY\u25be", "USD", "RFR", "BVOL", "Cube", "(Default", ")"]),
            "USD RFR BVOL Cube (Default)",
        ),
        ((["CCY\u25be", "USD", "RFR", "BVOL", "Cube"]), "USD RFR BVOL Cube"),
    ],
)
def test_a_split_parenthetical_suffix_is_still_captured_whole(
    boxes: list[str], expected: str
) -> None:
    """Codex review, PR #182.

    Taking a single token after the anchor dropped the suffix whenever the
    reader returned ``(Default)`` as separate boxes, and the shortened name
    was stored as resolved metadata. How OCR groups boxes varies by screen,
    so the name must not depend on it.
    """

    tokens = _curve_line_tokens(boxes) + _header_line("ATM Swaptions", 44.0) + grid_tokens()

    assert parse(tokens).metadata.curve_config == expected


def test_a_suffix_that_never_closes_leaves_the_field_unresolved() -> None:
    """Better unresolved than a name missing what the screen displayed."""

    tokens = (
        _curve_line_tokens(["CCY\u25be", "USD", "RFR", "BVOL", "Cube", "(Default"])
        + _header_line("ATM Swaptions", 44.0)
        + grid_tokens()
    )

    metadata = parse(tokens).metadata

    assert metadata.curve_config is None
    assert "curve_config" in metadata.unresolved_fields


def test_a_menu_action_returned_as_one_detection_is_still_not_a_curve_config() -> None:
    """Codex review, PR #182.

    The exclusion checked for a marker occupying its own token, so a reader
    that returned ``9) Analyze Cube`` as a single detection had the menu
    action stored as the resolved configuration name.
    """

    tokens = (
        _curve_line_tokens(["9) Analyze Cube"])
        + _header_line("ATM Swaptions", 44.0)
        + grid_tokens()
    )

    metadata = parse(tokens).metadata

    assert metadata.curve_config is None
    assert "curve_config" in metadata.unresolved_fields


def test_a_menu_action_ending_in_cube_is_never_a_curve_config() -> None:
    """'Analyze Cube' is a clickable action, not a configuration value."""

    tokens = _header_line("9) Analyze Cube 1) Caps/Floors 3) ATM Swaptions", 20.0)
    tokens += grid_tokens()

    metadata = parse(tokens).metadata

    assert metadata.curve_config is None
    assert "curve_config" in metadata.unresolved_fields


def test_two_curve_config_values_still_leave_the_field_unresolved() -> None:
    """Segmenting menu actions away must not make the field credulous: two
    genuine candidates are still refused."""

    tokens = _live_layout_header_tokens() + grid_tokens()
    tokens += _header_line("EUR ESTR BVOL Cube (Default)", 92.0)

    metadata = parse(tokens).metadata

    assert metadata.curve_config is None
    assert "curve_config" in metadata.unresolved_fields


def test_metadata_reads_the_screen_header_verbatim() -> None:
    metadata = parse(canonical_tokens()).metadata

    assert metadata.currency == "USD"
    assert metadata.curve_config == "USD RFR BVOL Cube (Default)"
    assert metadata.side == "Mid"
    assert metadata.quote_date == "08/18/26"
    assert metadata.tab == "ATM Swaptions"
    assert metadata.vol_type == "Normal Vol (OIS)"
    assert metadata.source == "BVOL"
    assert metadata.unresolved_fields == ()


def test_metadata_that_cannot_be_read_is_marked_unresolved_and_not_invented() -> None:
    tokens = [
        token
        for token in canonical_tokens()
        if token.text not in {"Mid", "08/18/26", "Cube", "(Default)"}
    ]

    metadata = parse(tokens).metadata

    assert metadata.side is None
    assert metadata.quote_date is None
    assert metadata.curve_config is None
    assert set(metadata.unresolved_fields) == {"side", "quote_date", "curve_config"}


def test_two_candidate_dates_leave_the_date_unresolved_rather_than_guessing() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("08/19/26", 400.0, 50.0))

    metadata = parse(tokens).metadata

    assert metadata.quote_date is None
    assert "quote_date" in metadata.unresolved_fields


def test_metadata_survives_a_grid_that_failed_closed() -> None:
    tokens = [token for token in canonical_tokens() if token.text != "Expiry"]

    capture = parse(tokens)

    assert capture.grid is None
    assert capture.metadata.currency == "USD"
    assert capture.metadata.vol_type == "Normal Vol (OIS)"


def test_every_unresolved_metadata_field_is_a_known_field_name() -> None:
    capture = parse([_token("nothing", 10.0, 10.0)])

    assert set(capture.metadata.unresolved_fields) <= set(METADATA_FIELDS)
    assert capture.grid is None


def test_the_vol_type_is_carried_verbatim_and_never_relabelled() -> None:
    """Normal/yield vol must never be silently renamed to a price vol."""

    metadata = parse(canonical_tokens()).metadata

    assert metadata.vol_type == "Normal Vol (OIS)"
    assert "PRICE_VOL" not in str(metadata.to_dict())
