"""Structural tests for the VCUB OTM Swaptions / SABR template parser and
its multi-image merge (Issue #185).

Every fixture here is **synthetic**: the row labels are ordinary tenor
buckets, the strike headers are the ones the screen's own contract names,
and the numbers are generated by :func:`_synthetic_value` from row/column
indices. Nothing in this file is a Bloomberg screen capture, a Bloomberg
screen layout measurement, or a live market quote -- this repository is
public, so the real screenshots stay operator-local and are supplied by
path at live acceptance.

The token layer is where these tests bite, because that is the parser's own
contract: a reader hands it text with boxes, and everything Issue #185 cares
about -- coordinate exactness, fail-closed behaviour, and what happens when
two overlapping screenshots disagree -- is decided from those boxes alone.
"""

from __future__ import annotations

from collections.abc import Sequence

import pytest

from shiori_pricing_lab.data.bloomberg_vcub_capture import (
    VCUBCaptureProvenance,
    VCUBCaptureStatus,
    VCUBTextToken,
)
from shiori_pricing_lab.data.bloomberg_vcub_otm_capture import (
    EXPECTED_ROWS,
    EXPECTED_STRIKE_OFFSETS_BP,
    NORMAL_VOL_SKEW_TYPE,
    OTM_METADATA_FIELDS,
    OTM_SWAPTIONS_SABR_TAB,
    PARSER_NAME,
    PARSER_VERSION,
    SPREAD_DISPLAY_MODE,
)
from shiori_pricing_lab.data.bloomberg_vcub_otm_template import (
    DuplicateCaptureImageError,
    merge_vcub_otm_reads,
    parse_vcub_otm_tokens,
)

# ---------------------------------------------------------------------------
# Synthetic fixture
# ---------------------------------------------------------------------------

#: The strike axis the observed screen draws, left to right.
STRIKE_LABELS = (
    "-200bps",
    "-100bps",
    "-50bps",
    "-25bps",
    "ATM",
    "25bps",
    "50bps",
    "100bps",
    "200bps",
)

#: The screen's own complete row set: the 91 ``Term x Tenor`` coordinates
#: the parser is required to reconstruct before a capture may be confirmed.
#: Taken from the production constant rather than restated, so a fixture can
#: never quietly disagree with the template the check reads.
ROW_LABELS = EXPECTED_ROWS

_HEADER_Y = 110.0
_FIRST_ROW_Y = 140.0
_ROW_PITCH = 24.0
_FIRST_COLUMN_RIGHT = 240.0
_COLUMN_PITCH = 76.0
_ANCHOR_LEFT = 40.0
_GLYPH_HEIGHT = 12.0
_CHARACTER_WIDTH = 8.0
_WORD_GAP = 4.0


def _synthetic_value(row_index: int, column_index: int) -> float:
    """A made-up, strictly distinct number per intersection -- never a quote.

    Deliberately signed: on the observed screen every column but ATM holds a
    spread, and several of them are negative, so the fixture must not prove
    the mapping only for positive numbers.
    """

    return round(-4.0 + row_index * 2.5 + column_index * 0.25, 2)


def _token(
    text: str,
    *,
    right: float,
    y_center: float,
    left: float | None = None,
) -> VCUBTextToken:
    width = len(text) * _CHARACTER_WIDTH if left is None else right - left
    return VCUBTextToken(
        text=text,
        left=right - width,
        top=y_center - _GLYPH_HEIGHT / 2.0,
        width=width,
        height=_GLYPH_HEIGHT,
        confidence=0.99,
    )


def _left_aligned(text: str, *, left: float, y_center: float) -> VCUBTextToken:
    return _token(text, right=left + len(text) * _CHARACTER_WIDTH, y_center=y_center)


def _row_y(row_index: int) -> float:
    return _FIRST_ROW_Y + row_index * _ROW_PITCH


def _column_right(column_index: int) -> float:
    return _FIRST_COLUMN_RIGHT + column_index * _COLUMN_PITCH


def _word_row(words: Sequence[str], y: float, left: float = 40.0) -> list[VCUBTextToken]:
    """One header line laid out with realistic intra-phrase spacing."""

    tokens: list[VCUBTextToken] = []
    cursor = left
    for word in words:
        tokens.append(_left_aligned(word, left=cursor, y_center=y))
        cursor += len(word) * _CHARACTER_WIDTH + _WORD_GAP
    return tokens


#: How far apart two *widgets* sit on a Bloomberg header line, against the
#: word gap inside one. Both are read off the boxes by the shared widget
#: rule, so a fixture that spaced its selectors like words would prove the
#: metadata rules against a screen Bloomberg never draws.
_WIDGET_GAP = 40.0


def _widget_row(
    widgets: Sequence[Sequence[str]], y: float, left: float = 40.0
) -> list[VCUBTextToken]:
    """One header line of separate selectors, each of several words."""

    tokens: list[VCUBTextToken] = []
    cursor = left
    for widget in widgets:
        tokens.extend(_word_row(widget, y, left=cursor))
        width = sum(len(word) * _CHARACTER_WIDTH for word in widget)
        cursor += width + _WORD_GAP * (len(widget) - 1) + _WIDGET_GAP
    return tokens


def chrome_tokens(
    *,
    vol_type: Sequence[str] = ("Normal", "Vol", "Skew▾"),
    source: str = "BVOL▾",
    display_mode: str = "Spread▾",
) -> list[VCUBTextToken]:
    """The header context above the matrix.

    The tab strip, then the three selectors this screen shows: a labelled
    ``Type``, a labelled ``Source``, and the display-mode dropdown that
    carries no label of its own.
    """

    return (
        _word_row(("11)", "Configuration", "13)", "ATM", "Swaptions", "14)", "OTM",
                   "Swaptions", "/", "SABR"), 20.0)
        + _widget_row(
            (("Type",), vol_type, ("Source",), (source,), (display_mode,)), 50.0
        )
        + _widget_row(((("Table",), ("Charts",))), 80.0)
    )


def chrome_tokens_with_selector_row(widgets: Sequence[Sequence[str]]) -> list[VCUBTextToken]:
    """The tab strip plus a hand-built selector widget row.

    For constructing Source/display-mode edge cases :func:`chrome_tokens`
    cannot represent on its own -- a missing contributor widget, or a row
    cropped right after it -- by passing exactly the widgets that line
    should carry (Codex review, PR #186).
    """

    return _word_row(
        ("11)", "Configuration", "13)", "ATM", "Swaptions", "14)", "OTM",
         "Swaptions", "/", "SABR"), 20.0
    ) + _widget_row(widgets, 50.0)


def matrix_tokens(
    *,
    rows: Sequence[int] | None = None,
    omit_cells: frozenset[tuple[int, int]] = frozenset(),
    omit_row_labels: frozenset[int] = frozenset(),
    value_overrides: dict[tuple[int, int], str] | None = None,
    strike_labels: Sequence[str] = STRIKE_LABELS,
) -> list[VCUBTextToken]:
    """The matrix itself: the corner anchor, both axes, and every cell.

    ``rows`` selects which of :data:`ROW_LABELS` this screenshot shows,
    which is how one long table is sliced into overlapping images. The rows
    keep their own y positions so a slice looks exactly like the part of the
    screen it came from.
    """

    value_overrides = value_overrides or {}
    row_indices = list(range(len(ROW_LABELS))) if rows is None else list(rows)

    tokens = _word_row(("Term", "x", "Tenor"), _HEADER_Y, left=_ANCHOR_LEFT)
    for column_index, label in enumerate(strike_labels):
        tokens.append(
            _token(label, right=_column_right(column_index), y_center=_HEADER_Y)
        )
    # Drawn at their position in *this* screenshot, not at their index in the
    # whole table: a screenshot of rows 40-70 starts at the top of its own
    # crop, and a screen that genuinely does not carry a row simply draws the
    # rows it does have one after another. Laying them out by table index
    # instead would leave a gap wherever a row was left out, which the pitch
    # check reads -- correctly -- as a row label the reader missed, and no
    # test of *coverage* could then be told apart from a test of geometry.
    for position, row_index in enumerate(row_indices):
        term, tenor = ROW_LABELS[row_index]
        if row_index not in omit_row_labels:
            tokens.extend(
                _word_row((term, "X", tenor), _row_y(position), left=_ANCHOR_LEFT)
            )
        for column_index in range(len(strike_labels)):
            if (row_index, column_index) in omit_cells:
                continue
            text = value_overrides.get(
                (row_index, column_index),
                f"{_synthetic_value(row_index, column_index):.2f}",
            )
            tokens.append(
                _token(text, right=_column_right(column_index), y_center=_row_y(position))
            )
    return tokens


def screenshot_tokens(*, chrome: dict | None = None, **kwargs) -> list[VCUBTextToken]:
    return chrome_tokens(**(chrome or {})) + matrix_tokens(**kwargs)


def provenance(reference: str = "otm.png", digest_seed: str = "a") -> VCUBCaptureProvenance:
    return VCUBCaptureProvenance(
        source_reference=reference,
        source_image_sha256=digest_seed * 64,
        source_image_bytes=2048,
        captured_at="2026-08-21T09:30:00Z",
        parser_name=PARSER_NAME,
        parser_version=PARSER_VERSION,
    )


def read(tokens: Sequence[VCUBTextToken], reference="otm.png", digest_seed="a"):
    return parse_vcub_otm_tokens(
        tokens, provenance=provenance(reference, digest_seed)
    )


def codes(issues) -> list[str]:
    return [issue.code for issue in issues]


# ---------------------------------------------------------------------------
# One screenshot: the coordinate contract
# ---------------------------------------------------------------------------


def test_the_canonical_synthetic_screen_parses_with_no_blocking_errors() -> None:
    parsed = read(screenshot_tokens())

    assert parsed.blocking_errors == ()
    assert parsed.table is not None
    assert parsed.table.strike_labels == STRIKE_LABELS
    assert parsed.table.row_labels == tuple(
        f"{term} x {tenor}" for term, tenor in ROW_LABELS
    )


def test_every_value_lands_on_its_own_row_and_strike_coordinate() -> None:
    table = read(screenshot_tokens()).table
    assert table is not None

    for row_index, (term, tenor) in enumerate(ROW_LABELS):
        for column_index, strike in enumerate(STRIKE_LABELS):
            assert table.value_at(term, tenor, strike) == pytest.approx(
                _synthetic_value(row_index, column_index)
            ), f"{term} x {tenor} at {strike}"


def test_the_first_and_last_coordinates_are_exact() -> None:
    """The corners are checked by name, not only by the sweep above."""

    table = read(screenshot_tokens()).table
    assert table is not None

    first_term, first_tenor = ROW_LABELS[0]
    last_term, last_tenor = ROW_LABELS[-1]
    assert (first_term, first_tenor) == ("1Mo", "1Yr")
    assert (last_term, last_tenor) == ("30Yr", "30Yr")
    assert table.value_at(first_term, first_tenor, "-200bps") == pytest.approx(
        _synthetic_value(0, 0)
    )
    assert table.value_at(first_term, first_tenor, "ATM") == pytest.approx(
        _synthetic_value(0, 4)
    )
    assert table.value_at(last_term, last_tenor, "200bps") == pytest.approx(
        _synthetic_value(len(ROW_LABELS) - 1, len(STRIKE_LABELS) - 1)
    )


def test_the_atm_column_is_the_only_one_without_a_strike_offset() -> None:
    table = read(screenshot_tokens()).table
    assert table is not None

    offsets = {strike.label: strike.offset_bp for strike in table.strikes}
    assert offsets == {
        "-200bps": -200.0,
        "-100bps": -100.0,
        "-50bps": -50.0,
        "-25bps": -25.0,
        "ATM": None,
        "25bps": 25.0,
        "50bps": 50.0,
        "100bps": 100.0,
        "200bps": 200.0,
    }


def test_a_missing_cell_does_not_shift_its_neighbours() -> None:
    """Issue #185's safety invariant, on the strike axis."""

    table = read(screenshot_tokens(omit_cells=frozenset({(5, 4)}))).table
    assert table is not None

    term, tenor = ROW_LABELS[5]
    assert table.value_at(term, tenor, "ATM") is None
    assert table.value_at(term, tenor, "-25bps") == pytest.approx(_synthetic_value(5, 3))
    assert table.value_at(term, tenor, "25bps") == pytest.approx(_synthetic_value(5, 5))
    # And the rows either side are untouched.
    assert table.value_at(*ROW_LABELS[4], "ATM") == pytest.approx(_synthetic_value(4, 4))
    assert table.value_at(*ROW_LABELS[6], "ATM") == pytest.approx(_synthetic_value(6, 4))


def test_a_whole_missing_row_of_values_does_not_shift_the_rows_below_it() -> None:
    omitted = frozenset((6, column) for column in range(len(STRIKE_LABELS)))
    table = read(screenshot_tokens(omit_cells=omitted)).table
    assert table is not None

    assert all(value is None for value in table.rows[6].values)
    assert table.value_at(*ROW_LABELS[7], "-200bps") == pytest.approx(_synthetic_value(7, 0))


def test_a_dropped_interior_row_label_fails_the_capture_closed() -> None:
    parsed = read(screenshot_tokens(omit_row_labels=frozenset({5})))

    assert "ROW_PITCH_IRREGULAR" in codes(parsed.blocking_errors)


def test_a_screenshot_cropped_through_its_last_row_fails_closed() -> None:
    """The row label went with the crop; its numbers did not."""

    tokens = screenshot_tokens(omit_row_labels=frozenset({len(ROW_LABELS) - 1}))
    parsed = read(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_ROWS" in codes(parsed.blocking_errors)


def test_a_malformed_number_blocks_rather_than_being_coerced() -> None:
    parsed = read(screenshot_tokens(value_overrides={(2, 3): "8O.15"}))

    assert "MALFORMED_NUMERIC_CELL" in codes(parsed.blocking_errors)


def test_a_non_finite_number_blocks() -> None:
    parsed = read(screenshot_tokens(value_overrides={(2, 3): "NaN"}))

    assert "NON_FINITE_NUMERIC_CELL" in codes(parsed.blocking_errors)


def test_a_missing_strike_header_fails_the_capture_closed() -> None:
    """The header went, its column's numbers stayed where they were drawn."""

    tokens = [
        token
        for token in screenshot_tokens()
        if not (token.text == "-50bps" and token.top < _FIRST_ROW_Y)
    ]
    parsed = read(tokens)

    assert "STRIKE_COLUMN_PITCH_IRREGULAR" in codes(parsed.blocking_errors)


def test_a_duplicated_strike_header_fails_the_capture_closed() -> None:
    labels = list(STRIKE_LABELS)
    labels[5] = "-50bps"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "DUPLICATE_STRIKE_HEADER" in codes(parsed.blocking_errors)


def test_a_strike_axis_without_an_atm_column_fails_closed() -> None:
    labels = list(STRIKE_LABELS)
    labels[4] = "10bps"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "ATM_STRIKE_COLUMN_UNRESOLVED" in codes(parsed.blocking_errors)


def test_strike_headers_out_of_order_fail_closed() -> None:
    labels = list(STRIKE_LABELS)
    labels[1] = "-300bps"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "STRIKE_HEADERS_NOT_MONOTONIC" in codes(parsed.blocking_errors)


def test_an_unreadable_strike_header_blocks_rather_than_shifting_columns() -> None:
    labels = list(STRIKE_LABELS)
    labels[2] = "-50 bp%"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "STRIKE_HEADER_UNEXPECTED_TOKEN" in codes(parsed.blocking_errors)


def test_row_labels_out_of_order_fail_closed() -> None:
    """The screen's rows must increase in term, then in tenor."""

    swapped = list(range(len(ROW_LABELS)))
    swapped[3], swapped[4] = swapped[4], swapped[3]
    parsed = read(screenshot_tokens(rows=swapped))

    assert "ROW_LABELS_NOT_MONOTONIC" in codes(parsed.blocking_errors)


def test_a_value_that_sits_between_two_strike_columns_is_refused() -> None:
    tokens = screenshot_tokens(omit_cells=frozenset({(3, 2)}))
    tokens.append(
        _token(
            "12.34",
            right=(_column_right(2) + _column_right(3)) / 2.0,
            y_center=_row_y(3),
        )
    )
    parsed = read(tokens)

    assert "CELL_POSITION_AMBIGUOUS" in codes(parsed.blocking_errors)


def test_two_values_read_into_one_cell_use_neither() -> None:
    tokens = screenshot_tokens()
    tokens.append(_token("77.77", right=_column_right(1), y_center=_row_y(1)))
    parsed = read(tokens)

    assert "DUPLICATE_CELL" in codes(parsed.blocking_errors)
    assert parsed.table is not None
    assert parsed.table.value_at("1Mo", "2Yr", "-100bps") is None


def test_the_capture_is_scale_and_translation_tolerant() -> None:
    """Same screen, re-cropped and re-scaled: same coordinates, same values."""

    def moved(token: VCUBTextToken) -> VCUBTextToken:
        scale = 1.6
        return VCUBTextToken(
            text=token.text,
            left=token.left * scale + 37.0,
            top=token.top * scale - 11.0,
            width=token.width * scale,
            height=token.height * scale,
            confidence=token.confidence,
        )

    original = read(screenshot_tokens()).table
    rescaled = read([moved(token) for token in screenshot_tokens()]).table
    assert original is not None and rescaled is not None

    assert rescaled.to_dict() == original.to_dict()


def test_a_split_strike_header_reads_the_same_as_a_whole_one() -> None:
    """``-200bps`` in two boxes is the same header as ``-200bps`` in one."""

    tokens = [
        token
        for token in screenshot_tokens()
        if not (token.text == "-200bps" and token.top < _FIRST_ROW_Y)
    ]
    whole = _token("-200bps", right=_column_right(0), y_center=_HEADER_Y)
    tokens += [
        _token("-200", right=whole.left + 4 * _CHARACTER_WIDTH, y_center=_HEADER_Y),
        _token("bps", right=whole.right, y_center=_HEADER_Y),
    ]
    parsed = read(tokens)

    assert parsed.blocking_errors == ()
    assert parsed.table is not None
    assert parsed.table.strike_labels == STRIKE_LABELS


# ---------------------------------------------------------------------------
# One screenshot: metadata and value semantics
# ---------------------------------------------------------------------------


def test_the_screen_contract_is_read_off_the_screen() -> None:
    metadata = read(screenshot_tokens()).metadata

    assert metadata.tab == OTM_SWAPTIONS_SABR_TAB
    assert metadata.vol_type == NORMAL_VOL_SKEW_TYPE
    assert metadata.display_mode == SPREAD_DISPLAY_MODE
    assert metadata.source == "BVOL"


def test_metadata_the_screen_does_not_show_stays_unresolved() -> None:
    """The screenshots this issue targets do not show the top chrome."""

    metadata = read(screenshot_tokens()).metadata

    for field in ("currency", "curve_config", "side", "quote_date"):
        assert getattr(metadata, field) is None
        assert field in metadata.unresolved_fields
    assert set(metadata.unresolved_fields) <= set(OTM_METADATA_FIELDS)


def test_an_unreadable_display_mode_blocks_the_capture() -> None:
    """What the numbers *are* is not something to assume."""

    tokens = [token for token in screenshot_tokens() if token.text != "Spread▾"]
    parsed = read(tokens)

    assert "DISPLAY_MODE_UNRESOLVED" in codes(parsed.blocking_errors)


def test_a_display_mode_this_parser_has_never_seen_blocks_the_capture() -> None:
    """A mode this parser does not recognise is a real (if unsupported)
    reading -- distinct from the selector not being on screen at all -- so
    it names what was actually seen rather than reading as merely
    unresolved (Codex review, PR #186)."""

    parsed = read(screenshot_tokens(chrome={"display_mode": "Absolute▾"}))

    assert "UNSUPPORTED_DISPLAY_MODE" in codes(parsed.blocking_errors)
    assert parsed.metadata.display_mode == "Absolute"


def test_an_unsupported_display_mode_is_still_found_beside_a_misread_source() -> None:
    """The display-mode widget is anchored on the literal ``Source`` label,
    not on the contributor value matching a known source -- so a misread
    contributor (``BVOL`` -> ``BV0L``) must not hide an otherwise legible
    unsupported display-mode reading right next to it (Codex review, PR
    #186)."""

    parsed = read(
        screenshot_tokens(chrome={"source": "BV0L▾", "display_mode": "Absolute▾"})
    )

    assert "UNSUPPORTED_DISPLAY_MODE" in codes(parsed.blocking_errors)
    assert parsed.metadata.display_mode == "Absolute"
    assert parsed.metadata.source is None


def test_a_missing_contributor_widget_blocks_rather_than_guessing_the_display_mode() -> None:
    """Regression 3: Source is visible but its contributor widget is
    entirely absent from OCR (not merely misread), so only one widget
    follows Source instead of two -- there is no way to tell from the
    token stream alone whether that lone widget is the missing
    contributor or the display mode, and this must fail closed rather
    than guess either way (Eddy's adjudication on Codex's P2, PR #186)."""

    tokens = chrome_tokens_with_selector_row(
        (("Type",), ("Normal", "Vol", "Skew▾"), ("Source",), ("Absolute▾",))
    ) + matrix_tokens()
    parsed = read(tokens)

    assert "DISPLAY_MODE_CONTEXT_AMBIGUOUS" in codes(parsed.blocking_errors)
    assert parsed.metadata.display_mode is None


def test_a_row_cropped_after_the_contributor_never_reads_bvol_as_the_display_mode() -> None:
    """Regression 4: Source and a legible contributor are both present, but
    the row is cropped before the display-mode widget -- the same
    ambiguity as above, from the other direction. This must still block,
    and must never mistake the contributor's own value (``BVOL``) for the
    display mode (Eddy's adjudication on Codex's P2, PR #186)."""

    tokens = chrome_tokens_with_selector_row(
        (("Type",), ("Normal", "Vol", "Skew▾"), ("Source",), ("BVOL▾",))
    ) + matrix_tokens()
    parsed = read(tokens)

    assert "DISPLAY_MODE_CONTEXT_AMBIGUOUS" in codes(parsed.blocking_errors)
    assert parsed.metadata.display_mode is None


def test_an_unsupported_vol_type_blocks_the_capture() -> None:
    parsed = read(
        screenshot_tokens(chrome={"vol_type": ("Lognormal", "Vol", "Skew▾")})
    )

    assert "UNSUPPORTED_VOL_TYPE" in codes(parsed.blocking_errors)


def test_a_missing_tab_anchor_blocks_the_capture() -> None:
    tokens = [
        token
        for token in screenshot_tokens()
        if token.top > 30.0  # drop the tab strip entirely
    ]
    parsed = read(tokens)

    assert "OTM_SABR_TAB_UNRESOLVED" in codes(parsed.blocking_errors)


def test_a_missing_corner_anchor_blocks_and_reconstructs_nothing() -> None:
    tokens = [
        token
        for token in screenshot_tokens()
        if token.text not in {"Term", "x", "Tenor"} or token.top > _HEADER_Y + 5
    ]
    parsed = read(tokens)

    assert "TERM_TENOR_ANCHOR_UNRESOLVED" in codes(parsed.blocking_errors)
    assert parsed.table is None


# ---------------------------------------------------------------------------
# Several screenshots: one capture
# ---------------------------------------------------------------------------

#: Three vertically overlapping slices covering the whole table, the way an
#: operator takes them: each one starts a few rows before the previous one
#: ended, and together they hold every expected row.
SLICE_A = range(0, 38)
SLICE_B = range(34, 70)
SLICE_C = range(66, len(ROW_LABELS))

#: A row each pair of adjacent slices both shows, and a row only one shows.
OVERLAP_AB = 35
OVERLAP_BC = 67


def _three_slices() -> list:
    return [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(screenshot_tokens(rows=SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]


def test_three_overlapping_screenshots_reconstruct_one_whole_surface() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert capture.blocking_errors == ()
    assert capture.table is not None
    assert capture.table.row_labels == tuple(
        f"{term} x {tenor}" for term, tenor in ROW_LABELS
    )
    assert capture.table.strike_labels == STRIKE_LABELS
    for row_index, (term, tenor) in enumerate(ROW_LABELS):
        for column_index, strike in enumerate(STRIKE_LABELS):
            assert capture.table.value_at(term, tenor, strike) == pytest.approx(
                _synthetic_value(row_index, column_index)
            )


def test_the_file_order_does_not_decide_the_market_data_order() -> None:
    forwards = merge_vcub_otm_reads(_three_slices())
    backwards = merge_vcub_otm_reads(list(reversed(_three_slices())))

    assert backwards.table is not None and forwards.table is not None
    assert backwards.table.to_dict() == forwards.table.to_dict()


def test_overlapping_rows_are_deduplicated_not_repeated() -> None:
    capture = merge_vcub_otm_reads(_three_slices())
    assert capture.table is not None

    labels = capture.table.row_labels
    assert len(labels) == len(set(labels)) == len(ROW_LABELS)


def test_the_capture_records_what_each_screenshot_contributed() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    coverage = {item.source_reference: item for item in capture.coverage}
    assert set(coverage) == {"shot-a.png", "shot-b.png", "shot-c.png"}
    assert coverage["shot-a.png"].row_labels[0] == "1Mo x 1Yr"
    assert coverage["shot-c.png"].row_labels[-1] == "30Yr x 30Yr"
    # Exactly the rows two screenshots both showed, named as such.
    shared_ab = {f"{term} x {tenor}" for term, tenor in ROW_LABELS[34:38]}
    assert set(coverage["shot-a.png"].shared_row_labels) == shared_ab
    assert shared_ab <= set(coverage["shot-b.png"].shared_row_labels)


def test_one_capture_session_keeps_every_source_image() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert [source.source_reference for source in capture.sources] == [
        "shot-a.png",
        "shot-b.png",
        "shot-c.png",
    ]
    assert len({source.source_image_sha256 for source in capture.sources}) == 3


def _slices_with(read_b_overrides: dict) -> list:
    """The three covering slices, with one of them reading a cell differently."""

    return [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, value_overrides=read_b_overrides),
            reference="shot-b.png",
            digest_seed="b",
        ),
        read(screenshot_tokens(rows=SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]


def test_two_screenshots_disagreeing_on_a_value_block_the_whole_capture() -> None:
    capture = merge_vcub_otm_reads(_slices_with({(OVERLAP_AB, 2): "99.99"}))

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "OVERLAP_VALUE_CONFLICT"
    ]
    assert len(conflicts) == 1
    assert conflicts[0].row == f"{ROW_LABELS[OVERLAP_AB][0]} x {ROW_LABELS[OVERLAP_AB][1]}"
    assert conflicts[0].strike == "-50bps"
    assert capture.can_confirm is False


def test_a_conflicting_overlap_never_prefers_one_screenshot() -> None:
    capture = merge_vcub_otm_reads(_slices_with({(OVERLAP_AB, 2): "99.99"}))

    with pytest.raises(ValueError, match="blocking errors"):
        capture.confirm(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")


def test_a_cell_one_screenshot_missed_is_filled_from_the_one_that_read_it() -> None:
    reads = [
        read(
            screenshot_tokens(rows=SLICE_A, omit_cells=frozenset({(OVERLAP_AB, 6)})),
            reference="shot-a.png",
            digest_seed="a",
        ),
        read(screenshot_tokens(rows=SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(screenshot_tokens(rows=SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert capture.blocking_errors == ()
    label = f"{ROW_LABELS[OVERLAP_AB][0]} x {ROW_LABELS[OVERLAP_AB][1]}"
    assert capture.table is not None
    assert capture.table.value_at(*ROW_LABELS[OVERLAP_AB], "50bps") == pytest.approx(
        _synthetic_value(OVERLAP_AB, 6)
    )
    partials = [
        issue for issue in capture.warnings if issue.code == "OVERLAP_PARTIAL_CELL"
    ]
    assert [(issue.row, issue.strike) for issue in partials] == [(label, "50bps")]


def test_screenshots_disagreeing_on_the_strike_axis_block() -> None:
    labels = list(STRIKE_LABELS)
    labels[0] = "-150bps"
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, strike_labels=labels),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "STRIKE_HEADERS_DISAGREE" in codes(capture.blocking_errors)
    assert capture.table is None


def test_strike_headers_with_different_casing_do_not_conflict() -> None:
    """OCR casing on the ``bps`` suffix must not discard an otherwise
    agreeing strike axis and its whole merged table (Codex review, PR
    #186)."""

    uppercase_labels = [label.upper() for label in STRIKE_LABELS]
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, strike_labels=uppercase_labels),
            reference="shot-b.png",
            digest_seed="b",
        ),
        read(screenshot_tokens(rows=SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "STRIKE_HEADERS_DISAGREE" not in codes(capture.blocking_errors)
    assert capture.table is not None
    assert capture.table.strike_labels == STRIKE_LABELS
    assert capture.can_confirm is True


def test_a_genuinely_different_strike_axis_still_conflicts() -> None:
    """The casing fix must not weaken a real strike-axis disagreement."""

    different_offsets = list(STRIKE_LABELS)
    different_offsets[0] = "-150bps"
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, strike_labels=different_offsets),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "STRIKE_HEADERS_DISAGREE" in codes(capture.blocking_errors)
    assert capture.table is None


def test_screenshots_disagreeing_on_metadata_block() -> None:
    other_source = screenshot_tokens(rows=SLICE_B, chrome={"source": "CMPN▾"})
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(other_source, reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "METADATA_CONFLICT"
    ]
    assert len(conflicts) == 1
    assert "source" in conflicts[0].message


def test_a_field_one_screenshot_could_not_read_resolves_from_the_other() -> None:
    """Not every screenshot has to repeat every piece of Bloomberg chrome."""

    without_chrome = matrix_tokens(rows=SLICE_B) + _word_row(
        ("14)", "OTM", "Swaptions", "/", "SABR"), 20.0
    )
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(without_chrome, reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert capture.metadata.source == "BVOL"
    assert capture.metadata.display_mode == SPREAD_DISPLAY_MODE
    # The second screenshot could not read them on its own, and said so.
    assert "display_mode" in reads[1].metadata.unresolved_fields


def test_a_visibly_unsupported_display_mode_still_blocks_even_when_another_resolves() -> None:
    """A screenshot that omits the display selector is safely filled from
    another image (the test above); one that *shows* an unsupported mode is
    a different screen state and must never be silently overridden by
    another image's supported reading (Codex review, PR #186)."""

    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, chrome={"display_mode": "Absolute▾"}),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "METADATA_CONFLICT"
    ]
    assert len(conflicts) == 1
    assert "display_mode" in conflicts[0].message
    assert capture.can_confirm is False


def test_a_visibly_unsupported_display_mode_still_blocks_beside_a_misread_source() -> None:
    """The exact failure mode above, but with the second image's own Source
    contributor misread (``BVOL`` -> ``BV0L``) too -- the display-mode
    reading must still be seen and still block, rather than the misread
    contributor hiding it and letting the first image's ``Spread`` silently
    win the merge (Codex review, PR #186)."""

    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(
                rows=SLICE_B, chrome={"source": "BV0L▾", "display_mode": "Absolute▾"}
            ),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "METADATA_CONFLICT"
    ]
    assert any("display_mode" in issue.message for issue in conflicts)
    assert capture.can_confirm is False


def test_screenshots_that_do_not_overlap_cannot_prove_nothing_was_skipped() -> None:
    reads = [
        read(screenshot_tokens(rows=range(0, 4)), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=range(8, 12)), reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "IMAGE_COVERAGE_GAP" in codes(capture.blocking_errors)


def test_the_same_screenshot_supplied_twice_is_refused() -> None:
    twice = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=SLICE_A), reference="copy.png", digest_seed="a"),
    ]

    with pytest.raises(DuplicateCaptureImageError):
        merge_vcub_otm_reads(twice)


def test_one_screenshot_is_a_perfectly_good_capture_session() -> None:
    capture = merge_vcub_otm_reads([read(screenshot_tokens())])

    assert capture.blocking_errors == ()
    assert capture.can_confirm is True
    assert len(capture.sources) == 1


def test_a_screenshot_that_failed_its_own_topology_blocks_the_session() -> None:
    capture = merge_vcub_otm_reads(_slices_with({(SLICE_B[1], 1): "8O.15"}))

    blockers = [
        issue for issue in capture.blocking_errors if issue.code == "MALFORMED_NUMERIC_CELL"
    ]
    assert len(blockers) == 1
    assert blockers[0].source == "shot-b.png"


# ---------------------------------------------------------------------------
# Selector metadata across a session (Codex review, PR #186)
# ---------------------------------------------------------------------------


def _without_type_and_display(rows: Sequence[int]) -> list[VCUBTextToken]:
    """A crop showing only the tab strip and the table -- no Type, Source, or
    Display selectors -- the way a lower, table-only screenshot reads. The
    intended workflow only puts that chrome in the first screenshot."""

    return matrix_tokens(rows=rows) + _word_row(
        ("14)", "OTM", "Swaptions", "/", "SABR"), 20.0
    )


def _three_slices_with_chrome(chrome_by_slice: dict[int, dict]) -> list:
    """The three covering slices, each with its own header chrome overrides.

    ``chrome_by_slice`` maps a slice index (0, 1, 2) to the ``chrome=``
    keyword :func:`screenshot_tokens` accepts for that slice; a slice not
    named keeps the canonical chrome.
    """

    slices = (SLICE_A, SLICE_B, SLICE_C)
    references = ("shot-a.png", "shot-b.png", "shot-c.png")
    seeds = ("a", "b", "c")
    return [
        read(
            screenshot_tokens(rows=rows, chrome=chrome_by_slice.get(index)),
            reference=references[index],
            digest_seed=seeds[index],
        )
        for index, rows in enumerate(slices)
    ]


def test_selector_blockers_from_one_image_do_not_survive_a_merge_that_resolves_them() -> None:
    """Regression A: only the first screenshot carries Type/Display; the two
    lower screenshots omit both, the way a table-only crop reads. The merged
    complete 91 x 9 capture has no selector blocker and can Confirm."""

    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(_without_type_and_display(SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(_without_type_and_display(SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]
    assert "VOL_TYPE_UNRESOLVED" in codes(reads[1].blocking_errors)
    assert "DISPLAY_MODE_UNRESOLVED" in codes(reads[1].blocking_errors)
    assert "VOL_TYPE_UNRESOLVED" in codes(reads[2].blocking_errors)
    assert "DISPLAY_MODE_UNRESOLVED" in codes(reads[2].blocking_errors)

    capture = merge_vcub_otm_reads(reads)

    assert capture.blocking_errors == ()
    assert capture.can_confirm is True
    assert capture.table is not None
    assert capture.table.row_labels == tuple(
        f"{term} x {tenor}" for term, tenor in ROW_LABELS
    )
    assert len(capture.table.row_labels) == 91
    assert len(capture.table.row_labels) * len(capture.table.strike_labels) == 91 * 9


def test_a_session_where_nothing_resolves_type_or_display_still_blocks() -> None:
    """Regression B: every screenshot omits Type and Display; the merged
    capture still blocks."""

    reads = [
        read(_without_type_and_display(SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(_without_type_and_display(SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(_without_type_and_display(SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "VOL_TYPE_UNRESOLVED" in codes(capture.blocking_errors)
    assert "DISPLAY_MODE_UNRESOLVED" in codes(capture.blocking_errors)
    assert capture.can_confirm is False


def test_normal_vol_skew_read_in_a_different_case_does_not_conflict() -> None:
    """Regression C: "Normal Vol Skew" and "NORMAL VOL SKEW" are one OCR
    reading, not a metadata conflict, and the merge is deterministic."""

    forwards = merge_vcub_otm_reads(
        _three_slices_with_chrome({1: {"vol_type": ("NORMAL", "VOL", "SKEW▾")}})
    )
    backwards = merge_vcub_otm_reads(
        list(reversed(_three_slices_with_chrome({1: {"vol_type": ("NORMAL", "VOL", "SKEW▾")}})))
    )

    assert "METADATA_CONFLICT" not in codes(forwards.blocking_errors)
    assert forwards.metadata.vol_type == NORMAL_VOL_SKEW_TYPE
    assert forwards.can_confirm is True
    assert backwards.metadata.vol_type == NORMAL_VOL_SKEW_TYPE


def test_genuinely_different_vol_types_still_conflict() -> None:
    """Regression D: a real disagreement between screenshots still blocks."""

    capture = merge_vcub_otm_reads(
        _three_slices_with_chrome({1: {"vol_type": ("Lognormal", "Vol", "Skew▾")}})
    )

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "METADATA_CONFLICT"
    ]
    assert len(conflicts) == 1
    assert "vol_type" in conflicts[0].message
    assert capture.can_confirm is False


def test_real_per_image_blockers_survive_alongside_an_omitted_selector() -> None:
    """Regression E: the selector-merge fix must not suppress a genuine
    topology/OCR/numeric blocker reported by another image in the session."""

    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(_without_type_and_display(SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(
            screenshot_tokens(rows=SLICE_C, value_overrides={(80, 1): "8O.15"}),
            reference="shot-c.png",
            digest_seed="c",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "MALFORMED_NUMERIC_CELL" in codes(capture.blocking_errors)
    assert "VOL_TYPE_UNRESOLVED" not in codes(capture.blocking_errors)
    assert "DISPLAY_MODE_UNRESOLVED" not in codes(capture.blocking_errors)
    assert capture.can_confirm is False


def test_a_lower_screenshot_without_the_source_label_stays_session_resolvable() -> None:
    """Regression 1: a screenshot that never shows the Source/display region
    at all -- the intended lower-crop workflow -- is unaffected by the
    context-gate fix. Its unresolved display mode is still safely filled
    from another screenshot, and DISPLAY_MODE_CONTEXT_AMBIGUOUS is never
    raised for it (Eddy's adjudication on Codex's P2, PR #186)."""

    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(_without_type_and_display(SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(_without_type_and_display(SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]
    assert "DISPLAY_MODE_CONTEXT_AMBIGUOUS" not in codes(reads[1].blocking_errors)
    assert "DISPLAY_MODE_CONTEXT_AMBIGUOUS" not in codes(reads[2].blocking_errors)

    capture = merge_vcub_otm_reads(reads)

    assert capture.blocking_errors == ()
    assert capture.can_confirm is True


def test_a_display_mode_context_ambiguity_survives_merge_even_when_another_resolves() -> None:
    """Regression 2: unlike an absent selector, a screenshot that shows
    Source but cannot confirm the display-mode widget's position must
    still block the whole session, even when another screenshot resolves
    Spread cleanly -- DISPLAY_MODE_CONTEXT_AMBIGUOUS is not one of the
    selector-resolution codes the merge is allowed to drop (Eddy's
    adjudication on Codex's P2, PR #186)."""

    ambiguous_chrome = chrome_tokens_with_selector_row(
        (("Type",), ("Normal", "Vol", "Skew▾"), ("Source",), ("Absolute▾",))
    )
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            ambiguous_chrome + matrix_tokens(rows=SLICE_B),
            reference="shot-b.png",
            digest_seed="b",
        ),
        read(screenshot_tokens(rows=SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "DISPLAY_MODE_CONTEXT_AMBIGUOUS" in codes(capture.blocking_errors)
    assert capture.can_confirm is False


def test_a_capture_starts_pending_and_accepts_nothing_until_confirmed() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert capture.review_status is VCUBCaptureStatus.PENDING_REVIEW
    assert capture.accepted_table is None

    confirmed = capture.confirm(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")
    assert confirmed.accepted_table is confirmed.table
    assert confirmed.review_status is VCUBCaptureStatus.CONFIRMED


def test_a_rejected_capture_accepts_nothing() -> None:
    capture = merge_vcub_otm_reads(_three_slices())
    rejected = capture.reject(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")

    assert rejected.accepted_table is None
    assert rejected.review_status is VCUBCaptureStatus.REJECTED


def test_an_empty_capture_session_is_refused() -> None:
    with pytest.raises(ValueError, match="at least one screenshot"):
        merge_vcub_otm_reads([])


# ---------------------------------------------------------------------------
# Completeness: the whole expected surface, however many screenshots it took
# ---------------------------------------------------------------------------


def _missing_from(capture) -> tuple[str, ...]:
    assert capture.table is not None
    return capture.table.missing_expected_rows()


def test_the_expected_surface_is_the_screens_own_row_set() -> None:
    """13 terms x 7 tenors, and the check reads exactly that."""

    assert len(EXPECTED_ROWS) == 91
    assert EXPECTED_ROWS[0] == ("1Mo", "1Yr")
    assert EXPECTED_ROWS[-1] == ("30Yr", "30Yr")


def test_a_complete_capture_holds_every_expected_row_and_may_be_confirmed() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert capture.blocking_errors == ()
    assert _missing_from(capture) == ()
    assert capture.table is not None
    assert capture.table.is_complete is True
    assert len(capture.table.rows) == len(EXPECTED_ROWS) == 91
    assert capture.can_confirm is True


def test_one_screenshot_holding_the_whole_surface_may_be_confirmed() -> None:
    """The screenshot count is not the contract -- the row set is."""

    capture = merge_vcub_otm_reads([read(screenshot_tokens())])

    assert len(capture.sources) == 1
    assert capture.blocking_errors == ()
    assert capture.can_confirm is True


def test_a_missing_middle_row_blocks_and_names_it() -> None:
    absent = 45
    rows = [index for index in range(len(ROW_LABELS)) if index != absent]
    capture = merge_vcub_otm_reads([read(screenshot_tokens(rows=rows))])

    label = f"{ROW_LABELS[absent][0]} x {ROW_LABELS[absent][1]}"
    assert _missing_from(capture) == (label,)
    blockers = [
        issue for issue in capture.blocking_errors if issue.code == "INCOMPLETE_SURFACE"
    ]
    assert len(blockers) == 1
    assert label in blockers[0].message
    assert capture.can_confirm is False


def test_a_missing_first_row_blocks_and_names_it() -> None:
    capture = merge_vcub_otm_reads(
        [read(screenshot_tokens(rows=range(1, len(ROW_LABELS))))]
    )

    assert _missing_from(capture) == ("1Mo x 1Yr",)
    assert "INCOMPLETE_SURFACE" in codes(capture.blocking_errors)
    assert capture.can_confirm is False


def test_a_missing_last_row_blocks_and_names_it() -> None:
    capture = merge_vcub_otm_reads(
        [read(screenshot_tokens(rows=range(len(ROW_LABELS) - 1)))]
    )

    assert _missing_from(capture) == ("30Yr x 30Yr",)
    assert "INCOMPLETE_SURFACE" in codes(capture.blocking_errors)
    assert capture.can_confirm is False


def test_screenshots_that_overlap_correctly_but_cover_half_the_screen_still_block() -> None:
    """A clean, well-overlapped, *partial* session is exactly the case a
    screenshot-count rule would have waved through."""

    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=SLICE_B), reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "IMAGE_COVERAGE_GAP" not in codes(capture.blocking_errors)  # they do overlap
    assert "INCOMPLETE_SURFACE" in codes(capture.blocking_errors)
    covered = len(set(SLICE_A) | set(SLICE_B))
    assert len(_missing_from(capture)) == len(EXPECTED_ROWS) - covered
    assert _missing_from(capture)[0] == "15Yr x 1Yr"
    assert capture.can_confirm is False


def test_neither_the_number_of_screenshots_nor_their_order_decides_completeness() -> None:
    forwards = merge_vcub_otm_reads(_three_slices())
    backwards = merge_vcub_otm_reads(list(reversed(_three_slices())))
    one_image = merge_vcub_otm_reads([read(screenshot_tokens())])

    assert _missing_from(forwards) == _missing_from(backwards) == _missing_from(one_image) == ()
    assert forwards.can_confirm is backwards.can_confirm is one_image.can_confirm is True


def test_a_row_outside_the_expected_set_blocks_rather_than_widening_it() -> None:
    tokens = screenshot_tokens()
    # A label the template does not name, drawn one row below the last.
    tokens += _word_row(
        ("40Yr", "X", "30Yr"), _row_y(len(ROW_LABELS)), left=_ANCHOR_LEFT
    )
    tokens += [
        _token("1.00", right=_column_right(column), y_center=_row_y(len(ROW_LABELS)))
        for column in range(len(STRIKE_LABELS))
    ]
    capture = merge_vcub_otm_reads([read(tokens)])

    unexpected = [
        issue for issue in capture.blocking_errors if issue.code == "UNEXPECTED_ROW"
    ]
    assert [issue.row for issue in unexpected] == ["40Yr x 30Yr"]
    assert capture.can_confirm is False


def test_the_expected_strike_axis_is_the_screens_own_nine_columns() -> None:
    assert len(EXPECTED_STRIKE_OFFSETS_BP) == 9
    assert EXPECTED_STRIKE_OFFSETS_BP == (
        -200.0,
        -100.0,
        -50.0,
        -25.0,
        None,
        25.0,
        50.0,
        100.0,
        200.0,
    )


def test_every_screenshot_cropped_short_of_a_strike_column_blocks() -> None:
    """The other axis of the same completeness question.

    Cropping the right-hand column off *every* screenshot removes the header
    and its values together, so no gap is left for the pitch check and no
    stray number for the outside-column check: the rows are all there, and
    the surface is still short a coordinate.
    """

    narrow = STRIKE_LABELS[:-1]
    capture = merge_vcub_otm_reads(
        [read(screenshot_tokens(strike_labels=narrow))]
    )

    assert capture.table is not None
    assert len(capture.table.rows) == len(EXPECTED_ROWS)  # every row present
    assert capture.table.missing_expected_rows() == ()
    assert capture.table.missing_expected_strikes() == ("200bps",)
    assert "INCOMPLETE_STRIKE_AXIS" in codes(capture.blocking_errors)
    assert capture.can_confirm is False


def test_a_capture_of_the_atm_column_alone_is_not_the_surface() -> None:
    capture = merge_vcub_otm_reads(
        [read(screenshot_tokens(strike_labels=("ATM",)))]
    )

    assert capture.table is not None
    assert len(capture.table.missing_expected_strikes()) == 8
    assert capture.can_confirm is False


def test_a_strike_column_outside_the_axis_blocks_rather_than_widening_it() -> None:
    labels = list(STRIKE_LABELS)
    labels[-1] = "300bps"
    capture = merge_vcub_otm_reads([read(screenshot_tokens(strike_labels=labels))])

    unexpected = [
        issue
        for issue in capture.blocking_errors
        if issue.code == "UNEXPECTED_STRIKE_COLUMN"
    ]
    assert [issue.strike for issue in unexpected] == ["300bps"]
    assert capture.can_confirm is False


def test_a_conflict_names_the_screenshot_the_held_value_actually_came_from() -> None:
    """Three screenshots: the first leaves a cell unresolved, the second fills
    it, the third disagrees. The conflict must point at the second."""

    # All three screenshots must show the row, so that the first one showing
    # it is the one *without* the value.
    cell = (OVERLAP_BC, 3)
    reads = [
        read(
            screenshot_tokens(
                rows=range(SLICE_A[0], SLICE_B[-1] + 1), omit_cells=frozenset({cell})
            ),
            reference="shot-a.png",
            digest_seed="a",
        ),
        read(
            screenshot_tokens(rows=SLICE_B),
            reference="shot-b.png",
            digest_seed="b",
        ),
        read(
            screenshot_tokens(rows=SLICE_C, value_overrides={cell: "99.99"}),
            reference="shot-c.png",
            digest_seed="c",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "OVERLAP_VALUE_CONFLICT"
    ]
    assert len(conflicts) == 1
    # The value under dispute was supplied by shot-b, never by shot-a.
    assert "'shot-b.png'" in conflicts[0].message
    assert "'shot-c.png'" in conflicts[0].message
    assert "'shot-a.png'" not in conflicts[0].message


def test_a_partial_cell_warning_names_every_screenshot_that_lacked_it() -> None:
    cell = (OVERLAP_AB, 6)
    reads = [
        read(
            screenshot_tokens(rows=SLICE_A, omit_cells=frozenset({cell})),
            reference="shot-a.png",
            digest_seed="a",
        ),
        read(
            screenshot_tokens(rows=SLICE_B, omit_cells=frozenset({cell})),
            reference="shot-b.png",
            digest_seed="b",
        ),
        read(
            screenshot_tokens(rows=range(SLICE_A[0], len(ROW_LABELS))),
            reference="shot-c.png",
            digest_seed="c",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    partials = [
        issue for issue in capture.warnings if issue.code == "OVERLAP_PARTIAL_CELL"
    ]
    filled = [issue for issue in partials if issue.strike == "50bps"]
    assert filled, partials
    assert "'shot-c.png'" in filled[-1].message
    assert "shot-a.png" in filled[-1].message
    assert "shot-b.png" in filled[-1].message


def test_an_incomplete_capture_can_never_be_confirmed_even_by_hand() -> None:
    """Structural, not merely reported: the state machine refuses it too."""

    capture = merge_vcub_otm_reads(
        [read(screenshot_tokens(rows=range(len(ROW_LABELS) - 1)))]
    )

    with pytest.raises(ValueError, match="blocking errors"):
        capture.confirm(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")


def test_the_otm_capture_slice_never_reaches_the_pricing_package() -> None:
    """Transcription and merging must not touch a pricing path at all."""

    import json
    import subprocess
    import sys

    probe = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys, json;"
            "import shiori_pricing_lab.data.bloomberg_vcub_otm_template;"
            "import shiori_pricing_lab.data.bloomberg_vcub_otm_capture;"
            "import shiori_pricing_lab.data.bloomberg_vcub_screen_reader;"
            "print(json.dumps([name for name in sys.modules "
            "if name.startswith('shiori_pricing_lab.pricing')]))",
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    assert json.loads(probe.stdout) == []
