"""Structural tests for the VCUB ATM Swaptions template parser (Issue #181).

Every fixture here is **synthetic**: the labels are ordinary tenor buckets
and the numbers are generated by :func:`_synthetic_value` from row/column
indices. Nothing in this file is a Bloomberg screen capture, a Bloomberg
screen layout measurement, or a live market quote -- this repository is
public, so the real screenshot stays operator-local and is supplied by path
at live acceptance.

The token layer is where these tests bite, because that is the parser's own
contract: a reader hands it text with boxes, and everything Issue #181 cares
about (order, cell mapping, fail-closed behaviour, scale/crop independence)
is decided from those boxes alone. The small end-to-end image test lives in
``test_bloomberg_vcub_ocr.py``.
"""

from __future__ import annotations

import pytest

from shiori_pricing_lab.data.bloomberg_vcub_atm_template import (
    parse_vcub_atm_tokens,
)
from shiori_pricing_lab.data.bloomberg_vcub_capture import (
    METADATA_FIELDS,
    VCUBCaptureProvenance,
    VCUBCaptureStatus,
    VCUBTextToken,
)

# ---------------------------------------------------------------------------
# Synthetic fixture
# ---------------------------------------------------------------------------

EXPIRY_LABELS = ("1Mo", "2Mo", "3Mo", "6Mo", "9Mo", "1Yr", "18Mo", "2Yr")
TENOR_LABELS = ("1Yr", "2Yr", "3Yr", "4Yr", "5Yr", "6Yr")

_HEADER_Y = 110.0
_FIRST_ROW_Y = 140.0
_ROW_PITCH = 28.0
_FIRST_COLUMN_X = 160.0
_COLUMN_PITCH = 80.0
_ANCHOR_X = 40.0
_GLYPH_HEIGHT = 14.0


def _synthetic_value(row_index: int, column_index: int) -> float:
    """A made-up, strictly distinct number per intersection -- never a real quote."""

    return round(80.0 + row_index * 1.5 + column_index * 0.25, 2)


def _token(
    text: str, x_center: float, y_center: float, *, width: float | None = None
) -> VCUBTextToken:
    width = len(text) * 8.0 if width is None else width
    return VCUBTextToken(
        text=text,
        left=x_center - width / 2.0,
        top=y_center - _GLYPH_HEIGHT / 2.0,
        width=width,
        height=_GLYPH_HEIGHT,
        confidence=0.99,
    )


def _row_y(row_index: int) -> float:
    return _FIRST_ROW_Y + row_index * _ROW_PITCH


def _column_x(column_index: int) -> float:
    return _FIRST_COLUMN_X + column_index * _COLUMN_PITCH


def metadata_tokens() -> list[VCUBTextToken]:
    """The header context above the matrix, as separate word tokens."""

    tokens = [
        _token("USD", 60.0, 20.0),
        _token("RFR", 100.0, 20.0),
        _token("BVOL", 145.0, 20.0),
        _token("Cube", 195.0, 20.0),
        _token("(Default)", 260.0, 20.0),
        _token("ATM", 60.0, 50.0),
        _token("Swaptions", 130.0, 50.0),
        _token("Mid", 230.0, 50.0),
        _token("08/18/26", 300.0, 50.0),
        _token("Type", 60.0, 80.0),
        _token("Normal", 120.0, 80.0),
        _token("Vol", 165.0, 80.0),
        _token("(OIS)", 210.0, 80.0),
        _token("Source", 280.0, 80.0),
        _token("BVOL", 340.0, 80.0),
    ]
    return tokens


def grid_tokens(
    *,
    omit_cells: frozenset[tuple[int, int]] = frozenset(),
    value_overrides: dict[tuple[int, int], str] | None = None,
) -> list[VCUBTextToken]:
    """The matrix itself: the corner anchor, both axes, and every cell.

    Cell centres are nudged right of their header centres so the fixture
    never accidentally proves the mapping only for perfectly centred text.
    """

    value_overrides = value_overrides or {}
    tokens = [_token("Expiry", _ANCHOR_X + 22.0, _HEADER_Y, width=44.0)]
    for column_index, label in enumerate(TENOR_LABELS):
        tokens.append(_token(label, _column_x(column_index), _HEADER_Y))
    for row_index, label in enumerate(EXPIRY_LABELS):
        tokens.append(_token(label, _ANCHOR_X + 14.0, _row_y(row_index)))
    for row_index in range(len(EXPIRY_LABELS)):
        for column_index in range(len(TENOR_LABELS)):
            if (row_index, column_index) in omit_cells:
                continue
            text = value_overrides.get(
                (row_index, column_index),
                f"{_synthetic_value(row_index, column_index):.2f}",
            )
            tokens.append(
                _token(text, _column_x(column_index) + 6.0, _row_y(row_index))
            )
    return tokens


def outside_grid_tokens() -> list[VCUBTextToken]:
    """Chrome that must never become a cell: a footer and a right-hand caption."""

    return [
        _token("Zoom", 120.0, 400.0),
        _token("100%", 175.0, 400.0),
        _token("Scroll", 720.0, _row_y(2)),
    ]


def canonical_tokens(**kwargs) -> list[VCUBTextToken]:
    return metadata_tokens() + grid_tokens(**kwargs) + outside_grid_tokens()


def provenance(**overrides) -> VCUBCaptureProvenance:
    fields = {
        "source_reference": "vcub_atm_usd.png",
        "source_image_sha256": "a" * 64,
        "source_image_bytes": 4096,
        "captured_at": "2026-08-18T09:30:00Z",
    }
    fields.update(overrides)
    return VCUBCaptureProvenance(**fields)


def parse(tokens) -> object:
    return parse_vcub_atm_tokens(tokens, provenance=provenance())


def transform(tokens, *, scale: float = 1.0, dx: float = 0.0, dy: float = 0.0):
    """Re-render the same screen at another zoom/crop, as a real recapture would."""

    return [
        VCUBTextToken(
            text=token.text,
            left=token.left * scale + dx,
            top=token.top * scale + dy,
            width=token.width * scale,
            height=token.height * scale,
            confidence=token.confidence,
        )
        for token in tokens
    ]


def codes(issues) -> list[str]:
    return [issue.code for issue in issues]


# ---------------------------------------------------------------------------
# 1-4: the canonical grid, its axis order, and every cell mapping
# ---------------------------------------------------------------------------


def test_canonical_synthetic_atm_grid_parses_with_no_blocking_errors() -> None:
    capture = parse(canonical_tokens())

    assert codes(capture.blocking_errors) == []
    assert capture.grid is not None
    assert capture.review_status is VCUBCaptureStatus.PENDING_REVIEW


def test_expiry_labels_keep_the_screen_order_down_the_rows() -> None:
    capture = parse(canonical_tokens())

    assert capture.grid.expiry_labels == EXPIRY_LABELS


def test_tenor_labels_keep_the_screen_order_across_the_columns() -> None:
    capture = parse(canonical_tokens())

    assert capture.grid.tenor_labels == TENOR_LABELS


def test_every_value_lands_on_its_own_expiry_and_tenor_intersection() -> None:
    capture = parse(canonical_tokens())

    for row_index, expiry in enumerate(EXPIRY_LABELS):
        for column_index, tenor in enumerate(TENOR_LABELS):
            assert capture.grid.value_at(expiry, tenor) == pytest.approx(
                _synthetic_value(row_index, column_index)
            ), f"{expiry} x {tenor} is not the value drawn at that intersection"


def test_a_shuffled_token_order_changes_nothing_because_placement_is_geometric() -> None:
    tokens = canonical_tokens()
    shuffled = list(reversed(tokens))

    assert parse(shuffled).grid.to_dict() == parse(tokens).grid.to_dict()


# ---------------------------------------------------------------------------
# 5-7: missing and duplicated anchors fail closed
# ---------------------------------------------------------------------------


def test_a_missing_expiry_anchor_fails_closed_with_no_grid() -> None:
    tokens = [token for token in canonical_tokens() if token.text != "Expiry"]

    capture = parse(tokens)

    assert capture.grid is None
    assert "EXPIRY_ANCHOR_UNRESOLVED" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_missing_atm_swaptions_tab_anchor_fails_closed() -> None:
    tokens = [token for token in canonical_tokens() if token.text != "Swaptions"]

    capture = parse(tokens)

    assert "ATM_SWAPTIONS_TAB_UNRESOLVED" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_duplicated_expiry_anchor_fails_closed_rather_than_picking_one() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("Expiry", _ANCHOR_X + 22.0, 400.0, width=44.0))

    capture = parse(tokens)

    assert capture.grid is None
    assert "EXPIRY_ANCHOR_AMBIGUOUS" in codes(capture.blocking_errors)


def test_a_duplicated_tenor_header_fails_closed() -> None:
    tokens = metadata_tokens() + outside_grid_tokens()
    for token in grid_tokens():
        if token.text == "4Yr" and abs(token.y_center - _HEADER_Y) < 1.0:
            token = _token("3Yr", token.x_center, token.y_center)
        tokens.append(token)

    capture = parse(tokens)

    assert capture.grid is None
    assert "DUPLICATE_TENOR_LABEL" in codes(capture.blocking_errors)


def test_a_duplicated_expiry_label_fails_closed() -> None:
    tokens = metadata_tokens() + outside_grid_tokens()
    for token in grid_tokens():
        if token.text == "6Mo" and abs(token.x_center - (_ANCHOR_X + 14.0)) < 1.0:
            token = _token("3Mo", token.x_center, token.y_center)
        tokens.append(token)

    capture = parse(tokens)

    assert capture.grid is None
    assert "DUPLICATE_EXPIRY_LABEL" in codes(capture.blocking_errors)


def test_a_non_tenor_token_on_the_header_line_fails_closed() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("Beta", _column_x(6), _HEADER_Y))

    capture = parse(tokens)

    assert "TENOR_HEADER_UNEXPECTED_TOKEN" in codes(capture.blocking_errors)


# ---------------------------------------------------------------------------
# 8-9: malformed and non-finite numbers
# ---------------------------------------------------------------------------


def test_a_malformed_numeric_cell_is_surfaced_and_left_unresolved() -> None:
    capture = parse(canonical_tokens(value_overrides={(2, 3): "8S.15"}))

    blocking = [
        issue for issue in capture.blocking_errors if issue.code == "MALFORMED_NUMERIC_CELL"
    ]
    assert [(issue.expiry, issue.tenor) for issue in blocking] == [("3Mo", "4Yr")]
    assert capture.grid.value_at("3Mo", "4Yr") is None
    assert not capture.can_confirm


@pytest.mark.parametrize("text", ["NaN", "Infinity", "-inf", "1e999"])
def test_a_non_finite_or_exponent_cell_never_becomes_a_value(text: str) -> None:
    capture = parse(canonical_tokens(value_overrides={(1, 1): text}))

    assert codes(capture.blocking_errors) != []
    assert capture.grid.value_at("2Mo", "2Yr") is None
    assert not capture.can_confirm


def test_a_thousands_separated_number_still_reads_as_one_value() -> None:
    capture = parse(canonical_tokens(value_overrides={(0, 0): "1,234.50"}))

    assert capture.grid.value_at("1Mo", "1Yr") == pytest.approx(1234.50)
    assert codes(capture.blocking_errors) == []


# ---------------------------------------------------------------------------
# 10-11: holes must not shift anything
# ---------------------------------------------------------------------------


def test_a_missing_interior_cell_cannot_shift_the_cells_after_it() -> None:
    capture = parse(canonical_tokens(omit_cells=frozenset({(3, 2)})))

    assert capture.grid.value_at("6Mo", "3Yr") is None
    for column_index, tenor in enumerate(TENOR_LABELS):
        if tenor == "3Yr":
            continue
        assert capture.grid.value_at("6Mo", tenor) == pytest.approx(
            _synthetic_value(3, column_index)
        )


def test_a_partial_row_cannot_shift_the_rows_below_it() -> None:
    omitted = frozenset({(4, 1), (4, 2), (4, 3), (4, 4), (4, 5)})

    capture = parse(canonical_tokens(omit_cells=omitted))

    assert capture.grid.value_at("9Mo", "1Yr") == pytest.approx(
        _synthetic_value(4, 0)
    )
    for tenor in TENOR_LABELS[1:]:
        assert capture.grid.value_at("9Mo", tenor) is None
    for row_index, expiry in enumerate(EXPIRY_LABELS[5:], start=5):
        for column_index, tenor in enumerate(TENOR_LABELS):
            assert capture.grid.value_at(expiry, tenor) == pytest.approx(
                _synthetic_value(row_index, column_index)
            )


def test_an_unresolved_intersection_is_reported_to_the_trader_as_a_warning() -> None:
    capture = parse(canonical_tokens(omit_cells=frozenset({(2, 3)})))

    unresolved = [issue for issue in capture.warnings if issue.code == "UNRESOLVED_CELL"]
    assert [(issue.expiry, issue.tenor) for issue in unresolved] == [("3Mo", "4Yr")]


def test_a_row_shifted_against_the_detected_columns_fails_closed() -> None:
    """Half a column of drift must be refused, never rounded to a neighbour."""

    tokens = metadata_tokens() + outside_grid_tokens()
    for token in grid_tokens():
        drifted = abs(token.y_center - _row_y(3)) < 1.0 and token.x_center > _FIRST_COLUMN_X - 40
        tokens.append(
            _token(token.text, token.x_center + _COLUMN_PITCH / 2.0, token.y_center)
            if drifted
            else token
        )

    capture = parse(tokens)

    assert "CELL_POSITION_AMBIGUOUS" in codes(capture.blocking_errors)
    assert not capture.can_confirm


def test_a_dropped_row_label_fails_closed_instead_of_shifting_a_row_up() -> None:
    """The one way a value could land a row out: a label the reader missed."""

    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == "6Mo" and abs(token.x_center - (_ANCHOR_X + 14.0)) < 1.0)
    ]

    capture = parse(tokens)

    assert codes(capture.blocking_errors) != []
    assert not capture.can_confirm


def test_a_dropped_tenor_header_fails_closed_instead_of_shifting_a_column_left() -> None:
    tokens = [
        token
        for token in canonical_tokens()
        if not (token.text == "3Yr" and abs(token.y_center - _HEADER_Y) < 1.0)
    ]

    capture = parse(tokens)

    assert codes(capture.blocking_errors) != []
    assert not capture.can_confirm


def test_two_values_read_into_one_intersection_fail_closed() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("99.99", _column_x(2) + 2.0, _row_y(1)))

    capture = parse(tokens)

    duplicates = [issue for issue in capture.blocking_errors if issue.code == "DUPLICATE_CELL"]
    assert [(issue.expiry, issue.tenor) for issue in duplicates] == [("2Mo", "3Yr")]
    assert capture.grid.value_at("2Mo", "3Yr") is None


def test_a_number_beside_the_matrix_is_reported_rather_than_placed() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("77.70", 720.0, _row_y(1)))

    capture = parse(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_COLUMNS" in codes(capture.blocking_errors)


# ---------------------------------------------------------------------------
# 12-13: scale and crop independence
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("scale", [0.8, 1.25, 1.5, 2.0])
def test_a_rescaled_capture_maps_every_cell_identically(scale: float) -> None:
    baseline = parse(canonical_tokens()).grid.to_dict()

    rescaled = parse(transform(canonical_tokens(), scale=scale)).grid.to_dict()

    assert rescaled == baseline


@pytest.mark.parametrize("dx,dy", [(-37.0, -52.0), (410.0, 260.0), (-19.5, 8.25)])
def test_a_recropped_or_repositioned_capture_maps_every_cell_identically(
    dx: float, dy: float
) -> None:
    baseline = parse(canonical_tokens()).grid.to_dict()

    moved = parse(transform(canonical_tokens(), dx=dx, dy=dy)).grid.to_dict()

    assert moved == baseline


def test_a_rescaled_and_recropped_capture_still_has_no_blocking_errors() -> None:
    capture = parse(transform(canonical_tokens(), scale=1.75, dx=-140.0, dy=-95.0))

    assert codes(capture.blocking_errors) == []
    assert capture.grid.value_at("3Mo", "4Yr") == pytest.approx(_synthetic_value(2, 3))


def test_small_per_token_jitter_does_not_move_a_value_into_a_neighbouring_cell() -> None:
    """Sub-pixel-ish detection wobble is normal and must not change any mapping."""

    tokens = canonical_tokens()
    jittered = [
        VCUBTextToken(
            text=token.text,
            left=token.left + (index % 5 - 2) * 0.9,
            top=token.top + (index % 3 - 1) * 0.7,
            width=token.width,
            height=token.height,
            confidence=token.confidence,
        )
        for index, token in enumerate(tokens)
    ]

    assert parse(jittered).grid.to_dict() == parse(tokens).grid.to_dict()


# ---------------------------------------------------------------------------
# 14: text outside the grid
# ---------------------------------------------------------------------------


def test_text_outside_the_matrix_never_becomes_a_cell() -> None:
    with_chrome = parse(canonical_tokens())
    without_chrome = parse(metadata_tokens() + grid_tokens())

    assert with_chrome.grid.to_dict() == without_chrome.grid.to_dict()
    assert codes(with_chrome.blocking_errors) == []


def test_a_stray_footer_number_below_the_matrix_is_not_a_cell() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("42.00", _column_x(1), _row_y(len(EXPIRY_LABELS)) + 60.0))

    capture = parse(tokens)

    assert codes(capture.blocking_errors) == []
    assert capture.grid.to_dict() == parse(canonical_tokens()).grid.to_dict()


# ---------------------------------------------------------------------------
# 15: metadata resolves or is explicitly unresolved, never invented
# ---------------------------------------------------------------------------


def test_metadata_reads_the_screen_header_verbatim() -> None:
    metadata = parse(canonical_tokens()).metadata

    assert metadata.currency == "USD"
    assert metadata.curve_config == "USD RFR BVOL Cube (Default)"
    assert metadata.side == "Mid"
    assert metadata.quote_date == "08/18/26"
    assert metadata.tab == "ATM Swaptions"
    assert metadata.vol_type == "Normal Vol (OIS)"
    assert metadata.source == "BVOL"
    assert metadata.unresolved_fields == ()


def test_metadata_that_cannot_be_read_is_marked_unresolved_and_not_invented() -> None:
    tokens = [
        token
        for token in canonical_tokens()
        if token.text not in {"Mid", "08/18/26", "Cube", "(Default)"}
    ]

    metadata = parse(tokens).metadata

    assert metadata.side is None
    assert metadata.quote_date is None
    assert metadata.curve_config is None
    assert set(metadata.unresolved_fields) == {"side", "quote_date", "curve_config"}


def test_two_candidate_dates_leave_the_date_unresolved_rather_than_guessing() -> None:
    tokens = canonical_tokens()
    tokens.append(_token("08/19/26", 400.0, 50.0))

    metadata = parse(tokens).metadata

    assert metadata.quote_date is None
    assert "quote_date" in metadata.unresolved_fields


def test_metadata_survives_a_grid_that_failed_closed() -> None:
    tokens = [token for token in canonical_tokens() if token.text != "Expiry"]

    capture = parse(tokens)

    assert capture.grid is None
    assert capture.metadata.currency == "USD"
    assert capture.metadata.vol_type == "Normal Vol (OIS)"


def test_every_unresolved_metadata_field_is_a_known_field_name() -> None:
    capture = parse([_token("nothing", 10.0, 10.0)])

    assert set(capture.metadata.unresolved_fields) <= set(METADATA_FIELDS)
    assert capture.grid is None


def test_the_vol_type_is_carried_verbatim_and_never_relabelled() -> None:
    """Normal/yield vol must never be silently renamed to a price vol."""

    metadata = parse(canonical_tokens()).metadata

    assert metadata.vol_type == "Normal Vol (OIS)"
    assert "PRICE_VOL" not in str(metadata.to_dict())
