"""Structural tests for the VCUB OTM Swaptions / SABR template parser and
its multi-image merge (Issue #185).

Every fixture here is **synthetic**: the row labels are ordinary tenor
buckets, the strike headers are the ones the screen's own contract names,
and the numbers are generated by :func:`_synthetic_value` from row/column
indices. Nothing in this file is a Bloomberg screen capture, a Bloomberg
screen layout measurement, or a live market quote -- this repository is
public, so the real screenshots stay operator-local and are supplied by
path at live acceptance.

The token layer is where these tests bite, because that is the parser's own
contract: a reader hands it text with boxes, and everything Issue #185 cares
about -- coordinate exactness, fail-closed behaviour, and what happens when
two overlapping screenshots disagree -- is decided from those boxes alone.
"""

from __future__ import annotations

from collections.abc import Sequence

import pytest

from shiori_pricing_lab.data.bloomberg_vcub_capture import (
    VCUBCaptureProvenance,
    VCUBCaptureStatus,
    VCUBTextToken,
)
from shiori_pricing_lab.data.bloomberg_vcub_otm_capture import (
    NORMAL_VOL_SKEW_TYPE,
    OTM_METADATA_FIELDS,
    OTM_SWAPTIONS_SABR_TAB,
    PARSER_NAME,
    PARSER_VERSION,
    SPREAD_DISPLAY_MODE,
)
from shiori_pricing_lab.data.bloomberg_vcub_otm_template import (
    DuplicateCaptureImageError,
    merge_vcub_otm_reads,
    parse_vcub_otm_tokens,
)

# ---------------------------------------------------------------------------
# Synthetic fixture
# ---------------------------------------------------------------------------

#: The strike axis the observed screen draws, left to right.
STRIKE_LABELS = (
    "-200bps",
    "-100bps",
    "-50bps",
    "-25bps",
    "ATM",
    "25bps",
    "50bps",
    "100bps",
    "200bps",
)

#: Twelve ``Term x Tenor`` rows in the screen's own order, spanning three
#: terms so a screenshot can be sliced anywhere without losing a whole term.
ROW_LABELS = (
    ("1Mo", "1Yr"),
    ("1Mo", "2Yr"),
    ("1Mo", "5Yr"),
    ("1Mo", "10Yr"),
    ("3Mo", "1Yr"),
    ("3Mo", "2Yr"),
    ("3Mo", "5Yr"),
    ("3Mo", "10Yr"),
    ("1Yr", "1Yr"),
    ("1Yr", "2Yr"),
    ("1Yr", "5Yr"),
    ("1Yr", "10Yr"),
)

_HEADER_Y = 110.0
_FIRST_ROW_Y = 140.0
_ROW_PITCH = 24.0
_FIRST_COLUMN_RIGHT = 240.0
_COLUMN_PITCH = 76.0
_ANCHOR_LEFT = 40.0
_GLYPH_HEIGHT = 12.0
_CHARACTER_WIDTH = 8.0
_WORD_GAP = 4.0


def _synthetic_value(row_index: int, column_index: int) -> float:
    """A made-up, strictly distinct number per intersection -- never a quote.

    Deliberately signed: on the observed screen every column but ATM holds a
    spread, and several of them are negative, so the fixture must not prove
    the mapping only for positive numbers.
    """

    return round(-4.0 + row_index * 1.5 + column_index * 0.25, 2)


def _token(
    text: str,
    *,
    right: float,
    y_center: float,
    left: float | None = None,
) -> VCUBTextToken:
    width = len(text) * _CHARACTER_WIDTH if left is None else right - left
    return VCUBTextToken(
        text=text,
        left=right - width,
        top=y_center - _GLYPH_HEIGHT / 2.0,
        width=width,
        height=_GLYPH_HEIGHT,
        confidence=0.99,
    )


def _left_aligned(text: str, *, left: float, y_center: float) -> VCUBTextToken:
    return _token(text, right=left + len(text) * _CHARACTER_WIDTH, y_center=y_center)


def _row_y(row_index: int) -> float:
    return _FIRST_ROW_Y + row_index * _ROW_PITCH


def _column_right(column_index: int) -> float:
    return _FIRST_COLUMN_RIGHT + column_index * _COLUMN_PITCH


def _word_row(words: Sequence[str], y: float, left: float = 40.0) -> list[VCUBTextToken]:
    """One header line laid out with realistic intra-phrase spacing."""

    tokens: list[VCUBTextToken] = []
    cursor = left
    for word in words:
        tokens.append(_left_aligned(word, left=cursor, y_center=y))
        cursor += len(word) * _CHARACTER_WIDTH + _WORD_GAP
    return tokens


#: How far apart two *widgets* sit on a Bloomberg header line, against the
#: word gap inside one. Both are read off the boxes by the shared widget
#: rule, so a fixture that spaced its selectors like words would prove the
#: metadata rules against a screen Bloomberg never draws.
_WIDGET_GAP = 40.0


def _widget_row(
    widgets: Sequence[Sequence[str]], y: float, left: float = 40.0
) -> list[VCUBTextToken]:
    """One header line of separate selectors, each of several words."""

    tokens: list[VCUBTextToken] = []
    cursor = left
    for widget in widgets:
        tokens.extend(_word_row(widget, y, left=cursor))
        width = sum(len(word) * _CHARACTER_WIDTH for word in widget)
        cursor += width + _WORD_GAP * (len(widget) - 1) + _WIDGET_GAP
    return tokens


def chrome_tokens(
    *,
    vol_type: Sequence[str] = ("Normal", "Vol", "Skew▾"),
    source: str = "BVOL▾",
    display_mode: str = "Spread▾",
) -> list[VCUBTextToken]:
    """The header context above the matrix.

    The tab strip, then the three selectors this screen shows: a labelled
    ``Type``, a labelled ``Source``, and the display-mode dropdown that
    carries no label of its own.
    """

    return (
        _word_row(("11)", "Configuration", "13)", "ATM", "Swaptions", "14)", "OTM",
                   "Swaptions", "/", "SABR"), 20.0)
        + _widget_row(
            (("Type",), vol_type, ("Source",), (source,), (display_mode,)), 50.0
        )
        + _widget_row(((("Table",), ("Charts",))), 80.0)
    )


def matrix_tokens(
    *,
    rows: Sequence[int] | None = None,
    omit_cells: frozenset[tuple[int, int]] = frozenset(),
    omit_row_labels: frozenset[int] = frozenset(),
    value_overrides: dict[tuple[int, int], str] | None = None,
    strike_labels: Sequence[str] = STRIKE_LABELS,
) -> list[VCUBTextToken]:
    """The matrix itself: the corner anchor, both axes, and every cell.

    ``rows`` selects which of :data:`ROW_LABELS` this screenshot shows,
    which is how one long table is sliced into overlapping images. The rows
    keep their own y positions so a slice looks exactly like the part of the
    screen it came from.
    """

    value_overrides = value_overrides or {}
    row_indices = list(range(len(ROW_LABELS))) if rows is None else list(rows)

    tokens = _word_row(("Term", "x", "Tenor"), _HEADER_Y, left=_ANCHOR_LEFT)
    for column_index, label in enumerate(strike_labels):
        tokens.append(
            _token(label, right=_column_right(column_index), y_center=_HEADER_Y)
        )
    for row_index in row_indices:
        term, tenor = ROW_LABELS[row_index]
        if row_index not in omit_row_labels:
            tokens.extend(
                _word_row((term, "X", tenor), _row_y(row_index), left=_ANCHOR_LEFT)
            )
        for column_index in range(len(strike_labels)):
            if (row_index, column_index) in omit_cells:
                continue
            text = value_overrides.get(
                (row_index, column_index),
                f"{_synthetic_value(row_index, column_index):.2f}",
            )
            tokens.append(
                _token(text, right=_column_right(column_index), y_center=_row_y(row_index))
            )
    return tokens


def screenshot_tokens(*, chrome: dict | None = None, **kwargs) -> list[VCUBTextToken]:
    return chrome_tokens(**(chrome or {})) + matrix_tokens(**kwargs)


def provenance(reference: str = "otm.png", digest_seed: str = "a") -> VCUBCaptureProvenance:
    return VCUBCaptureProvenance(
        source_reference=reference,
        source_image_sha256=digest_seed * 64,
        source_image_bytes=2048,
        captured_at="2026-08-21T09:30:00Z",
        parser_name=PARSER_NAME,
        parser_version=PARSER_VERSION,
    )


def read(tokens: Sequence[VCUBTextToken], reference="otm.png", digest_seed="a"):
    return parse_vcub_otm_tokens(
        tokens, provenance=provenance(reference, digest_seed)
    )


def codes(issues) -> list[str]:
    return [issue.code for issue in issues]


# ---------------------------------------------------------------------------
# One screenshot: the coordinate contract
# ---------------------------------------------------------------------------


def test_the_canonical_synthetic_screen_parses_with_no_blocking_errors() -> None:
    parsed = read(screenshot_tokens())

    assert parsed.blocking_errors == ()
    assert parsed.table is not None
    assert parsed.table.strike_labels == STRIKE_LABELS
    assert parsed.table.row_labels == tuple(
        f"{term} x {tenor}" for term, tenor in ROW_LABELS
    )


def test_every_value_lands_on_its_own_row_and_strike_coordinate() -> None:
    table = read(screenshot_tokens()).table
    assert table is not None

    for row_index, (term, tenor) in enumerate(ROW_LABELS):
        for column_index, strike in enumerate(STRIKE_LABELS):
            assert table.value_at(term, tenor, strike) == pytest.approx(
                _synthetic_value(row_index, column_index)
            ), f"{term} x {tenor} at {strike}"


def test_the_first_and_last_coordinates_are_exact() -> None:
    """The corners are checked by name, not only by the sweep above."""

    table = read(screenshot_tokens()).table
    assert table is not None

    assert table.value_at("1Mo", "1Yr", "-200bps") == pytest.approx(_synthetic_value(0, 0))
    assert table.value_at("1Mo", "1Yr", "ATM") == pytest.approx(_synthetic_value(0, 4))
    assert table.value_at("1Yr", "10Yr", "200bps") == pytest.approx(
        _synthetic_value(len(ROW_LABELS) - 1, len(STRIKE_LABELS) - 1)
    )


def test_the_atm_column_is_the_only_one_without_a_strike_offset() -> None:
    table = read(screenshot_tokens()).table
    assert table is not None

    offsets = {strike.label: strike.offset_bp for strike in table.strikes}
    assert offsets == {
        "-200bps": -200.0,
        "-100bps": -100.0,
        "-50bps": -50.0,
        "-25bps": -25.0,
        "ATM": None,
        "25bps": 25.0,
        "50bps": 50.0,
        "100bps": 100.0,
        "200bps": 200.0,
    }


def test_a_missing_cell_does_not_shift_its_neighbours() -> None:
    """Issue #185's safety invariant, on the strike axis."""

    table = read(screenshot_tokens(omit_cells=frozenset({(5, 4)}))).table
    assert table is not None

    assert table.value_at("3Mo", "2Yr", "ATM") is None
    assert table.value_at("3Mo", "2Yr", "-25bps") == pytest.approx(_synthetic_value(5, 3))
    assert table.value_at("3Mo", "2Yr", "25bps") == pytest.approx(_synthetic_value(5, 5))
    # And the rows either side are untouched.
    assert table.value_at("3Mo", "1Yr", "ATM") == pytest.approx(_synthetic_value(4, 4))
    assert table.value_at("3Mo", "5Yr", "ATM") == pytest.approx(_synthetic_value(6, 4))


def test_a_whole_missing_row_of_values_does_not_shift_the_rows_below_it() -> None:
    omitted = frozenset((6, column) for column in range(len(STRIKE_LABELS)))
    table = read(screenshot_tokens(omit_cells=omitted)).table
    assert table is not None

    assert all(value is None for value in table.rows[6].values)
    assert table.value_at("3Mo", "10Yr", "-200bps") == pytest.approx(_synthetic_value(7, 0))


def test_a_dropped_interior_row_label_fails_the_capture_closed() -> None:
    parsed = read(screenshot_tokens(omit_row_labels=frozenset({5})))

    assert "ROW_PITCH_IRREGULAR" in codes(parsed.blocking_errors)


def test_a_screenshot_cropped_through_its_last_row_fails_closed() -> None:
    """The row label went with the crop; its numbers did not."""

    tokens = screenshot_tokens(omit_row_labels=frozenset({len(ROW_LABELS) - 1}))
    parsed = read(tokens)

    assert "NUMERIC_TOKEN_OUTSIDE_ROWS" in codes(parsed.blocking_errors)


def test_a_malformed_number_blocks_rather_than_being_coerced() -> None:
    parsed = read(screenshot_tokens(value_overrides={(2, 3): "8O.15"}))

    assert "MALFORMED_NUMERIC_CELL" in codes(parsed.blocking_errors)


def test_a_non_finite_number_blocks() -> None:
    parsed = read(screenshot_tokens(value_overrides={(2, 3): "NaN"}))

    assert "NON_FINITE_NUMERIC_CELL" in codes(parsed.blocking_errors)


def test_a_missing_strike_header_fails_the_capture_closed() -> None:
    """The header went, its column's numbers stayed where they were drawn."""

    tokens = [
        token
        for token in screenshot_tokens()
        if not (token.text == "-50bps" and token.top < _FIRST_ROW_Y)
    ]
    parsed = read(tokens)

    assert "STRIKE_COLUMN_PITCH_IRREGULAR" in codes(parsed.blocking_errors)


def test_a_duplicated_strike_header_fails_the_capture_closed() -> None:
    labels = list(STRIKE_LABELS)
    labels[5] = "-50bps"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "DUPLICATE_STRIKE_HEADER" in codes(parsed.blocking_errors)


def test_a_strike_axis_without_an_atm_column_fails_closed() -> None:
    labels = list(STRIKE_LABELS)
    labels[4] = "10bps"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "ATM_STRIKE_COLUMN_UNRESOLVED" in codes(parsed.blocking_errors)


def test_strike_headers_out_of_order_fail_closed() -> None:
    labels = list(STRIKE_LABELS)
    labels[1] = "-300bps"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "STRIKE_HEADERS_NOT_MONOTONIC" in codes(parsed.blocking_errors)


def test_an_unreadable_strike_header_blocks_rather_than_shifting_columns() -> None:
    labels = list(STRIKE_LABELS)
    labels[2] = "-50 bp%"
    parsed = read(screenshot_tokens(strike_labels=labels))

    assert "STRIKE_HEADER_UNEXPECTED_TOKEN" in codes(parsed.blocking_errors)


def test_row_labels_out_of_order_fail_closed() -> None:
    tokens = [
        token
        for token in screenshot_tokens()
        if not (token.text == "3Mo" and token.left < _FIRST_COLUMN_RIGHT)
    ]
    # Put a later term where an earlier one was drawn.
    tokens += [
        _left_aligned("5Yr", left=_ANCHOR_LEFT, y_center=_row_y(row_index))
        for row_index in (4, 5, 6, 7)
    ]
    parsed = read(tokens)

    assert "ROW_LABELS_NOT_MONOTONIC" in codes(parsed.blocking_errors)


def test_a_value_that_sits_between_two_strike_columns_is_refused() -> None:
    tokens = screenshot_tokens(omit_cells=frozenset({(3, 2)}))
    tokens.append(
        _token(
            "12.34",
            right=(_column_right(2) + _column_right(3)) / 2.0,
            y_center=_row_y(3),
        )
    )
    parsed = read(tokens)

    assert "CELL_POSITION_AMBIGUOUS" in codes(parsed.blocking_errors)


def test_two_values_read_into_one_cell_use_neither() -> None:
    tokens = screenshot_tokens()
    tokens.append(_token("77.77", right=_column_right(1), y_center=_row_y(1)))
    parsed = read(tokens)

    assert "DUPLICATE_CELL" in codes(parsed.blocking_errors)
    assert parsed.table is not None
    assert parsed.table.value_at("1Mo", "2Yr", "-100bps") is None


def test_the_capture_is_scale_and_translation_tolerant() -> None:
    """Same screen, re-cropped and re-scaled: same coordinates, same values."""

    def moved(token: VCUBTextToken) -> VCUBTextToken:
        scale = 1.6
        return VCUBTextToken(
            text=token.text,
            left=token.left * scale + 37.0,
            top=token.top * scale - 11.0,
            width=token.width * scale,
            height=token.height * scale,
            confidence=token.confidence,
        )

    original = read(screenshot_tokens()).table
    rescaled = read([moved(token) for token in screenshot_tokens()]).table
    assert original is not None and rescaled is not None

    assert rescaled.to_dict() == original.to_dict()


def test_a_split_strike_header_reads_the_same_as_a_whole_one() -> None:
    """``-200bps`` in two boxes is the same header as ``-200bps`` in one."""

    tokens = [
        token
        for token in screenshot_tokens()
        if not (token.text == "-200bps" and token.top < _FIRST_ROW_Y)
    ]
    whole = _token("-200bps", right=_column_right(0), y_center=_HEADER_Y)
    tokens += [
        _token("-200", right=whole.left + 4 * _CHARACTER_WIDTH, y_center=_HEADER_Y),
        _token("bps", right=whole.right, y_center=_HEADER_Y),
    ]
    parsed = read(tokens)

    assert parsed.blocking_errors == ()
    assert parsed.table is not None
    assert parsed.table.strike_labels == STRIKE_LABELS


# ---------------------------------------------------------------------------
# One screenshot: metadata and value semantics
# ---------------------------------------------------------------------------


def test_the_screen_contract_is_read_off_the_screen() -> None:
    metadata = read(screenshot_tokens()).metadata

    assert metadata.tab == OTM_SWAPTIONS_SABR_TAB
    assert metadata.vol_type == NORMAL_VOL_SKEW_TYPE
    assert metadata.display_mode == SPREAD_DISPLAY_MODE
    assert metadata.source == "BVOL"


def test_metadata_the_screen_does_not_show_stays_unresolved() -> None:
    """The screenshots this issue targets do not show the top chrome."""

    metadata = read(screenshot_tokens()).metadata

    for field in ("currency", "curve_config", "side", "quote_date"):
        assert getattr(metadata, field) is None
        assert field in metadata.unresolved_fields
    assert set(metadata.unresolved_fields) <= set(OTM_METADATA_FIELDS)


def test_an_unreadable_display_mode_blocks_the_capture() -> None:
    """What the numbers *are* is not something to assume."""

    tokens = [token for token in screenshot_tokens() if token.text != "Spread▾"]
    parsed = read(tokens)

    assert "DISPLAY_MODE_UNRESOLVED" in codes(parsed.blocking_errors)


def test_a_display_mode_this_parser_has_never_seen_blocks_the_capture() -> None:
    parsed = read(screenshot_tokens(chrome={"display_mode": "Absolute▾"}))

    assert "DISPLAY_MODE_UNRESOLVED" in codes(parsed.blocking_errors)


def test_an_unsupported_vol_type_blocks_the_capture() -> None:
    parsed = read(
        screenshot_tokens(chrome={"vol_type": ("Lognormal", "Vol", "Skew▾")})
    )

    assert "UNSUPPORTED_VOL_TYPE" in codes(parsed.blocking_errors)


def test_a_missing_tab_anchor_blocks_the_capture() -> None:
    tokens = [
        token
        for token in screenshot_tokens()
        if token.top > 30.0  # drop the tab strip entirely
    ]
    parsed = read(tokens)

    assert "OTM_SABR_TAB_UNRESOLVED" in codes(parsed.blocking_errors)


def test_a_missing_corner_anchor_blocks_and_reconstructs_nothing() -> None:
    tokens = [
        token
        for token in screenshot_tokens()
        if token.text not in {"Term", "x", "Tenor"} or token.top > _HEADER_Y + 5
    ]
    parsed = read(tokens)

    assert "TERM_TENOR_ANCHOR_UNRESOLVED" in codes(parsed.blocking_errors)
    assert parsed.table is None


# ---------------------------------------------------------------------------
# Several screenshots: one capture
# ---------------------------------------------------------------------------

#: Three vertically overlapping slices of the same table, the way an
#: operator takes them: each one starts a couple of rows before the previous
#: one ended.
SLICE_A = range(0, 6)
SLICE_B = range(4, 10)
SLICE_C = range(8, 12)


def _three_slices() -> list:
    return [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=SLICE_B), reference="shot-b.png", digest_seed="b"),
        read(screenshot_tokens(rows=SLICE_C), reference="shot-c.png", digest_seed="c"),
    ]


def test_three_overlapping_screenshots_reconstruct_one_whole_surface() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert capture.blocking_errors == ()
    assert capture.table is not None
    assert capture.table.row_labels == tuple(
        f"{term} x {tenor}" for term, tenor in ROW_LABELS
    )
    assert capture.table.strike_labels == STRIKE_LABELS
    for row_index, (term, tenor) in enumerate(ROW_LABELS):
        for column_index, strike in enumerate(STRIKE_LABELS):
            assert capture.table.value_at(term, tenor, strike) == pytest.approx(
                _synthetic_value(row_index, column_index)
            )


def test_the_file_order_does_not_decide_the_market_data_order() -> None:
    forwards = merge_vcub_otm_reads(_three_slices())
    backwards = merge_vcub_otm_reads(list(reversed(_three_slices())))

    assert backwards.table is not None and forwards.table is not None
    assert backwards.table.to_dict() == forwards.table.to_dict()


def test_overlapping_rows_are_deduplicated_not_repeated() -> None:
    capture = merge_vcub_otm_reads(_three_slices())
    assert capture.table is not None

    labels = capture.table.row_labels
    assert len(labels) == len(set(labels)) == len(ROW_LABELS)


def test_the_capture_records_what_each_screenshot_contributed() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    coverage = {item.source_reference: item for item in capture.coverage}
    assert set(coverage) == {"shot-a.png", "shot-b.png", "shot-c.png"}
    assert coverage["shot-a.png"].row_labels[0] == "1Mo x 1Yr"
    assert set(coverage["shot-a.png"].shared_row_labels) == {"3Mo x 1Yr", "3Mo x 2Yr"}
    assert set(coverage["shot-c.png"].shared_row_labels) == {"1Yr x 1Yr", "1Yr x 2Yr"}


def test_one_capture_session_keeps_every_source_image() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert [source.source_reference for source in capture.sources] == [
        "shot-a.png",
        "shot-b.png",
        "shot-c.png",
    ]
    assert len({source.source_image_sha256 for source in capture.sources}) == 3


def test_two_screenshots_disagreeing_on_a_value_block_the_whole_capture() -> None:
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, value_overrides={(4, 2): "99.99"}),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "OVERLAP_VALUE_CONFLICT"
    ]
    assert len(conflicts) == 1
    assert conflicts[0].row == "3Mo x 1Yr"
    assert conflicts[0].strike == "-50bps"
    assert capture.can_confirm is False


def test_a_conflicting_overlap_never_prefers_one_screenshot() -> None:
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, value_overrides={(4, 2): "99.99"}),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    with pytest.raises(ValueError, match="blocking errors"):
        capture.confirm(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")


def test_a_cell_one_screenshot_missed_is_filled_from_the_one_that_read_it() -> None:
    reads = [
        read(
            screenshot_tokens(rows=SLICE_A, omit_cells=frozenset({(4, 6)})),
            reference="shot-a.png",
            digest_seed="a",
        ),
        read(screenshot_tokens(rows=SLICE_B), reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert capture.blocking_errors == ()
    assert capture.table is not None
    assert capture.table.value_at("3Mo", "1Yr", "50bps") == pytest.approx(
        _synthetic_value(4, 6)
    )
    partials = [
        issue for issue in capture.warnings if issue.code == "OVERLAP_PARTIAL_CELL"
    ]
    assert [(issue.row, issue.strike) for issue in partials] == [("3Mo x 1Yr", "50bps")]


def test_screenshots_disagreeing_on_the_strike_axis_block() -> None:
    labels = list(STRIKE_LABELS)
    labels[0] = "-150bps"
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(
            screenshot_tokens(rows=SLICE_B, strike_labels=labels),
            reference="shot-b.png",
            digest_seed="b",
        ),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "STRIKE_HEADERS_DISAGREE" in codes(capture.blocking_errors)
    assert capture.table is None


def test_screenshots_disagreeing_on_metadata_block() -> None:
    other_source = screenshot_tokens(rows=SLICE_B, chrome={"source": "CMPN▾"})
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(other_source, reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    conflicts = [
        issue for issue in capture.blocking_errors if issue.code == "METADATA_CONFLICT"
    ]
    assert len(conflicts) == 1
    assert "source" in conflicts[0].message


def test_a_field_one_screenshot_could_not_read_resolves_from_the_other() -> None:
    """Not every screenshot has to repeat every piece of Bloomberg chrome."""

    without_chrome = matrix_tokens(rows=SLICE_B) + _word_row(
        ("14)", "OTM", "Swaptions", "/", "SABR"), 20.0
    )
    reads = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(without_chrome, reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert capture.metadata.source == "BVOL"
    assert capture.metadata.display_mode == SPREAD_DISPLAY_MODE
    # The second screenshot could not read them on its own, and said so.
    assert "display_mode" in reads[1].metadata.unresolved_fields


def test_screenshots_that_do_not_overlap_cannot_prove_nothing_was_skipped() -> None:
    reads = [
        read(screenshot_tokens(rows=range(0, 4)), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=range(8, 12)), reference="shot-b.png", digest_seed="b"),
    ]
    capture = merge_vcub_otm_reads(reads)

    assert "IMAGE_COVERAGE_GAP" in codes(capture.blocking_errors)


def test_the_same_screenshot_supplied_twice_is_refused() -> None:
    twice = [
        read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"),
        read(screenshot_tokens(rows=SLICE_A), reference="copy.png", digest_seed="a"),
    ]

    with pytest.raises(DuplicateCaptureImageError):
        merge_vcub_otm_reads(twice)


def test_one_screenshot_is_a_perfectly_good_capture_session() -> None:
    capture = merge_vcub_otm_reads([read(screenshot_tokens())])

    assert capture.blocking_errors == ()
    assert capture.can_confirm is True
    assert len(capture.sources) == 1


def test_a_screenshot_that_failed_its_own_topology_blocks_the_session() -> None:
    broken = read(
        screenshot_tokens(rows=SLICE_B, value_overrides={(5, 1): "8O.15"}),
        reference="shot-b.png",
        digest_seed="b",
    )
    capture = merge_vcub_otm_reads(
        [read(screenshot_tokens(rows=SLICE_A), reference="shot-a.png", digest_seed="a"), broken]
    )

    blockers = [
        issue for issue in capture.blocking_errors if issue.code == "MALFORMED_NUMERIC_CELL"
    ]
    assert len(blockers) == 1
    assert blockers[0].source == "shot-b.png"


def test_a_capture_starts_pending_and_accepts_nothing_until_confirmed() -> None:
    capture = merge_vcub_otm_reads(_three_slices())

    assert capture.review_status is VCUBCaptureStatus.PENDING_REVIEW
    assert capture.accepted_table is None

    confirmed = capture.confirm(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")
    assert confirmed.accepted_table is confirmed.table
    assert confirmed.review_status is VCUBCaptureStatus.CONFIRMED


def test_a_rejected_capture_accepts_nothing() -> None:
    capture = merge_vcub_otm_reads(_three_slices())
    rejected = capture.reject(reviewed_by="Eddy", reviewed_at="2026-08-21T09:31:00Z")

    assert rejected.accepted_table is None
    assert rejected.review_status is VCUBCaptureStatus.REJECTED


def test_an_empty_capture_session_is_refused() -> None:
    with pytest.raises(ValueError, match="at least one screenshot"):
        merge_vcub_otm_reads([])


def test_the_otm_capture_slice_never_reaches_the_pricing_package() -> None:
    """Transcription and merging must not touch a pricing path at all."""

    import json
    import subprocess
    import sys

    probe = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys, json;"
            "import shiori_pricing_lab.data.bloomberg_vcub_otm_template;"
            "import shiori_pricing_lab.data.bloomberg_vcub_otm_capture;"
            "import shiori_pricing_lab.data.bloomberg_vcub_screen_reader;"
            "print(json.dumps([name for name in sys.modules "
            "if name.startswith('shiori_pricing_lab.pricing')]))",
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    assert json.loads(probe.stdout) == []
