"""Canonical JSON / fingerprint / invocation contract for the Rates bridge (Issue #227).

These tests pin the wire format that ``cpp/rates_engine/`` must reproduce byte for
byte: ECMAScript number formatting, UTF-8 key ordering, minimal escaping, SHA-256
fingerprints, and the small CLI-invocation surface's fail-closed error tokens.

The parity test at the end of the file consumes the tracked fixture file
``cpp/rates_engine/tests/fixtures/canonical_parity_fixtures.json``, generated by
``cpp/rates_engine/tests/fixtures/generate_parity_fixtures.py`` and asserted by the C++ suite too.
If the fixture is absent the test is *skipped* (never silently passed), so the absence of the
fixture cannot be mistaken for proven Python/C++ parity.
"""

from __future__ import annotations

import datetime
import hashlib
import json
from decimal import Decimal
from pathlib import Path

import pytest

from shiori_pricing_lab.rates_bridge import (
    SHA256_HEX_LENGTH,
    RatesEngineError,
    canonical_number,
    dumps,
    dumps_bytes,
    engine_identity,
    find_engine_cli,
    fingerprint,
    fingerprint_bytes,
    fingerprint_value,
    invoke,
    is_valid_fingerprint,
)

_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
_CANONICAL_PARITY_FIXTURES = (
    _REPOSITORY_ROOT
    / "cpp"
    / "rates_engine"
    / "tests"
    / "fixtures"
    / "canonical_parity_fixtures.json"
)

# ECMA-262 Number::toString anchors. Two entries are written with their decimal literal
# spelling (0.000001 / 0.0000001) even though they denote the same doubles as 1e-6 /
# 1e-7: the threshold must not depend on how the caller spelled the value. The 21/22 and
# -6/-7 pairs straddle the fixed/scientific boundaries in both directions.
_NUMBER_ANCHORS = [
    (100.0, "100"),
    (0.0425, "0.0425"),
    (123.456, "123.456"),
    (1e16, "10000000000000000"),
    (1e20, "100000000000000000000"),
    (1e21, "1e+21"),
    (1e22, "1e+22"),
    (1e-6, "0.000001"),
    (0.000001, "0.000001"),
    (1e-7, "1e-7"),
    (0.0000001, "1e-7"),
    (1.5e-7, "1.5e-7"),
    (2.5e-8, "2.5e-8"),
    (123456789012345680.0, "123456789012345680"),
    (-100.0, "-100"),
    (-0.0425, "-0.0425"),
    (-1e21, "-1e+21"),
    (-1e-7, "-1e-7"),
]

# A self-derived regression anchor: the digest of the canonical bytes below. It exists to
# make an accidental format change (escaping, separators, key order, number layout) fail
# loudly on the Python side, and to give the C++ side one exact expected digest.
_GOLDEN_DOCUMENT = {
    "schema_version": "RATES_KERNEL_INPUT_V1",
    "valuation_date": "2026-06-10",
    "is_probe": True,
}
_GOLDEN_CANONICAL = (
    '{"is_probe":true,"schema_version":"RATES_KERNEL_INPUT_V1","valuation_date":"2026-06-10"}'
)
_GOLDEN_FINGERPRINT = "6e0fe9eec68fe474c160d92733ffbd1650906511dcbbc083d130173355713fcc"


# --------------------------------------------------------------------------------------
# canonical_number -- ECMAScript Number::toString
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize(("value", "expected"), _NUMBER_ANCHORS)
def test_canonical_number_matches_ecmascript_anchors(value, expected):
    assert canonical_number(value) == expected


def test_canonical_number_renders_both_zeros_as_zero():
    assert canonical_number(0.0) == "0"
    assert canonical_number(-0.0) == "0"
    assert canonical_number(-0.0) == canonical_number(0.0)
    assert dumps(-0.0) == "0"


def test_canonical_number_keeps_shortest_round_tripping_digits():
    assert canonical_number(0.1) == "0.1"
    assert canonical_number(1.5) == "1.5"
    assert canonical_number(1000000.0) == "1000000"
    assert canonical_number(9.9e-5) == "0.000099"
    assert canonical_number(1 / 3) == "0.3333333333333333"
    assert float(canonical_number(0.1)) == 0.1
    assert float(canonical_number(123456789012345680.0)) == 123456789012345680.0
    assert float(canonical_number(1.5e-7)) == 1.5e-7


@pytest.mark.parametrize("value", [float("nan"), float("inf"), float("-inf")])
def test_canonical_number_rejects_non_finite_values(value):
    with pytest.raises(ValueError):
        canonical_number(value)
    with pytest.raises(ValueError):
        dumps(value)
    with pytest.raises(ValueError):
        dumps([value])


@pytest.mark.parametrize("value", [True, False, "1", None, [1], Decimal("1.5")])
def test_canonical_number_rejects_non_numbers(value):
    with pytest.raises(TypeError):
        canonical_number(value)


# --------------------------------------------------------------------------------------
# dumps -- canonical JSON text
# --------------------------------------------------------------------------------------


def test_dumps_sorts_object_keys_by_utf8_byte_order():
    # UTF-8 bytes of "é" are c3 a9, which is greater than "z" (7a) -- so "z" sorts
    # first. (UTF-8 byte order coincides with code-point order for well-formed text,
    # and deliberately differs from JavaScript's UTF-16 code-unit order; see the next
    # test for a case where the two orders disagree.)
    document = {"\u00e9": 1, "z": 2}
    assert dumps(document) == '{"z":2,"\u00e9":1}'
    assert dumps_bytes(document) == b'{"z":2,"\xc3\xa9":1}'


def test_dumps_key_order_is_utf8_not_utf16_code_units():
    # U+FFFD encodes as ef bf bd; U+1F600 encodes as f0 9f 98 80. UTF-8 order therefore
    # puts U+FFFD first, while UTF-16 code-unit order (lead surrogate d83d) would put the
    # emoji first. The canonical form is the UTF-8 one.
    assert dumps({"\U0001f600": 1, "\ufffd": 2}) == '{"\ufffd":2,"\U0001f600":1}'


def test_dumps_uses_fixed_separators_and_no_whitespace():
    assert dumps({"b": [1, 2.5, None], "a": {"nested": True}}) == (
        '{"a":{"nested":true},"b":[1,2.5,null]}'
    )
    assert dumps({}) == "{}"
    assert dumps(()) == "[]"
    assert dumps((1, 2)) == "[1,2]"
    assert dumps([{"k": "v"}, []]) == '[{"k":"v"},[]]'
    canonical = dumps({"a": {"b": [1, 2]}})
    assert " " not in canonical and "\n" not in canonical


def test_dumps_escapes_only_the_characters_json_requires():
    assert dumps('a"b\\c') == '"a\\"b\\\\c"'
    assert dumps("\b\f\n\r\t") == '"\\b\\f\\n\\r\\t"'
    assert dumps("\x00\x1f") == '"\\u0000\\u001f"'
    assert dumps({"a\nb": "c\td"}) == '{"a\\nb":"c\\td"}'


def test_dumps_emits_non_ascii_literally_not_escaped():
    assert dumps("é—中😀") == '"é—中😀"'
    assert dumps_bytes("é") == b'"\xc3\xa9"'
    assert dumps_bytes("中") == b'"\xe4\xb8\xad"'
    assert "\\u" not in dumps("é—中😀")


@pytest.mark.parametrize("value", ["\ud800", "\udfff", "a\ud834b", "\ud834"])
def test_dumps_rejects_lone_surrogates_in_strings(value):
    with pytest.raises(ValueError):
        dumps(value)
    with pytest.raises(ValueError):
        dumps_bytes(value)


def test_dumps_rejects_lone_surrogates_in_object_keys_and_nested_values():
    with pytest.raises(ValueError):
        dumps({"\ud800": 1})
    with pytest.raises(ValueError):
        dumps({"a": [{"b": "\udfff"}]})


def test_dumps_dispatches_bool_before_int():
    assert dumps(True) == "true"
    assert dumps(False) == "false"
    assert dumps(1) == "1"
    assert dumps(0) == "0"
    assert dumps([True, False, 1, 0]) == "[true,false,1,0]"
    assert dumps({"enabled": True, "count": 1}) == '{"count":1,"enabled":true}'


def test_dumps_collapses_integral_float_and_int_to_the_same_number():
    # dumps(1) and dumps(1.0) agree because ECMAScript Number::toString(1) is "1"; the
    # canonical form has one spelling per logical number, not one per Python type.
    assert dumps(1.0) == dumps(1) == "1"
    assert dumps([1.0, 1]) == "[1,1]"


def test_dumps_accepts_the_signed_64_bit_integer_bounds():
    assert dumps(2**63 - 1) == "9223372036854775807"
    assert dumps(-(2**63)) == "-9223372036854775808"
    assert dumps(0) == "0"


@pytest.mark.parametrize("value", [2**63, -(2**63) - 1, 10**30, -(10**30)])
def test_dumps_rejects_integers_outside_the_signed_64_bit_range(value):
    with pytest.raises(ValueError):
        dumps(value)
    with pytest.raises(ValueError):
        dumps({"amount": value})


@pytest.mark.parametrize(
    "value",
    [
        Decimal("1.5"),
        datetime.date(2026, 6, 10),
        datetime.datetime(2026, 6, 10, 16, 0, 0),
        b"bytes",
        bytearray(b"bytes"),
        {1, 2},
        complex(1.0, 2.0),
        object(),
        lambda: None,
    ],
)
def test_dumps_rejects_unsupported_types(value):
    with pytest.raises(TypeError):
        dumps(value)


def test_dumps_rejects_non_string_object_keys():
    with pytest.raises(TypeError):
        dumps({1: "a"})
    with pytest.raises(TypeError):
        dumps({"outer": {None: 1}})


def test_dumps_bytes_is_the_utf8_encoding_of_dumps():
    document = {"b": [1, "é", None], "a": True}
    assert dumps_bytes(document) == dumps(document).encode("utf-8")


def test_dumps_matches_the_golden_regression_anchor():
    assert dumps(_GOLDEN_DOCUMENT) == _GOLDEN_CANONICAL
    assert fingerprint_value(_GOLDEN_DOCUMENT) == _GOLDEN_FINGERPRINT


# --------------------------------------------------------------------------------------
# fingerprints
# --------------------------------------------------------------------------------------


def test_fingerprint_bytes_is_lowercase_sha256_of_the_given_bytes():
    payload = dumps_bytes({"b": 1, "a": "é"})
    assert fingerprint_bytes(payload) == hashlib.sha256(payload).hexdigest()
    assert fingerprint_bytes(bytearray(payload)) == hashlib.sha256(payload).hexdigest()
    assert fingerprint_bytes(payload) == fingerprint_bytes(payload)
    assert len(fingerprint_bytes(payload)) == SHA256_HEX_LENGTH == 64
    assert fingerprint_bytes(payload) == fingerprint_bytes(payload).lower()


@pytest.mark.parametrize("value", ["a string", None, 1, 1.5, ["bytes"]])
def test_fingerprint_bytes_rejects_non_bytes(value):
    with pytest.raises(TypeError):
        fingerprint_bytes(value)


def test_fingerprint_value_is_stable_across_key_insertion_order():
    first = {"b": 2, "a": {"y": [1, 2], "x": None}}
    second = {"a": {"x": None, "y": [1, 2]}, "b": 2}

    assert fingerprint_value(first) == fingerprint_value(second)
    assert fingerprint_value(first) == fingerprint_bytes(dumps_bytes(first))
    assert fingerprint_value(first) != fingerprint_value(
        {"b": 2, "a": {"y": [1, 3], "x": None}}
    )


def test_fingerprint_dispatches_between_serialized_payloads_and_values():
    document = {"a": [1, 2]}
    canonical_text = dumps(document)

    assert fingerprint(document) == fingerprint_value(document)
    assert fingerprint(canonical_text) == fingerprint_value(document)
    assert fingerprint(canonical_text.encode("utf-8")) == fingerprint_value(document)
    assert fingerprint(bytearray(canonical_text.encode("utf-8"))) == fingerprint_value(
        document
    )
    # A JSON *string value* is not the same payload as its canonical text.
    assert fingerprint_value("abc") != fingerprint("abc")


def test_is_valid_fingerprint_accepts_only_lowercase_sha256_hex():
    assert is_valid_fingerprint(fingerprint_value({"a": 1}))
    assert is_valid_fingerprint("0" * SHA256_HEX_LENGTH)
    assert is_valid_fingerprint("abcdef0123456789" * 4)

    assert not is_valid_fingerprint("A" * SHA256_HEX_LENGTH)
    assert not is_valid_fingerprint("a" * (SHA256_HEX_LENGTH - 1))
    assert not is_valid_fingerprint("a" * (SHA256_HEX_LENGTH + 1))
    assert not is_valid_fingerprint("g" * SHA256_HEX_LENGTH)
    assert not is_valid_fingerprint("")
    assert not is_valid_fingerprint(None)
    assert not is_valid_fingerprint(b"a" * SHA256_HEX_LENGTH)


# --------------------------------------------------------------------------------------
# engine invocation surface -- no built CLI is required for any assertion below
# --------------------------------------------------------------------------------------


def test_rates_engine_error_carries_code_message_and_detail():
    error = RatesEngineError(
        code="INVALID_KERNEL_INPUT",
        message="missing schema_version",
        detail={"field": "schema_version"},
    )

    assert error.code == "INVALID_KERNEL_INPUT"
    assert error.message == "missing schema_version"
    assert error.detail == {"field": "schema_version"}
    assert "INVALID_KERNEL_INPUT" in str(error)
    assert error.to_dict() == {
        "code": "INVALID_KERNEL_INPUT",
        "message": "missing schema_version",
        "detail": {"field": "schema_version"},
    }


def test_find_engine_cli_honours_an_existing_env_override(tmp_path, monkeypatch):
    discovered = tmp_path / "shiori_rates_cli"
    discovered.write_text("", encoding="utf-8")
    monkeypatch.setenv("SHIORI_RATES_ENGINE_CLI", str(discovered))

    assert find_engine_cli() == discovered


def test_find_engine_cli_never_fabricates_a_path(monkeypatch):
    monkeypatch.delenv("SHIORI_RATES_ENGINE_CLI", raising=False)

    resolved = find_engine_cli()

    assert resolved is None or (
        resolved.is_file() and resolved.name.startswith("shiori_rates_cli")
    )


def test_invoke_and_engine_identity_report_a_missing_cli(tmp_path):
    absent = tmp_path / "no_such_shiori_rates_cli"

    with pytest.raises(RatesEngineError) as invoke_error:
        invoke({"schema_version": "RATES_KERNEL_INPUT_V1"}, cli_path=absent)
    assert invoke_error.value.code == "ENGINE_CLI_NOT_FOUND"
    assert invoke_error.value.detail["operation"] == "validate-kernel-input"

    with pytest.raises(RatesEngineError) as identity_error:
        engine_identity(cli_path=absent)
    assert identity_error.value.code == "ENGINE_CLI_NOT_FOUND"
    assert identity_error.value.detail["operation"] == "engine-identity"


# --------------------------------------------------------------------------------------
# Python <-> C++ canonical parity fixtures.
#
# The fixture file is tracked and generated by
# ``cpp/rates_engine/tests/fixtures/generate_parity_fixtures.py`` (Python side, whose number form
# was verified against V8's ``String(number)``). Both languages assert against it, so a divergence
# between the two canonicalizers turns into a failing test on both sides rather than a silent
# fingerprint mismatch in production.
# --------------------------------------------------------------------------------------


@pytest.mark.skipif(
    not _CANONICAL_PARITY_FIXTURES.is_file(),
    reason=(
        "canonical parity fixtures are missing: "
        "cpp/rates_engine/tests/fixtures/canonical_parity_fixtures.json"
    ),
)
def test_python_matches_cpp_canonical_parity_fixtures():
    fixtures = json.loads(_CANONICAL_PARITY_FIXTURES.read_text(encoding="utf-8"))
    numbers = fixtures["numbers"]
    documents = fixtures["documents"]
    assert numbers or documents, "the parity fixture file carries no expectations"

    for entry in numbers:
        labeled = json.dumps(entry, sort_keys=True)
        assert canonical_number(float(entry["value"])) == entry["canonical"], labeled

    for entry in documents:
        assert dumps(entry["json"]) == entry["canonical"], entry["name"]
        assert fingerprint_value(entry["json"]) == entry["fingerprint"], entry["name"]
        assert is_valid_fingerprint(entry["fingerprint"]), entry["name"]
